# Chapter 9 (Levels 81 to 90) of arts.film_tv: data for build.py.
ACCESSED = "2026-09-27"

SOURCES = [
    ("source.brit_new_hollywood", "New Hollywood", "https://www.britannica.com/art/New-Hollywood", "Encyclopaedia Britannica",
     "Cited for: New Hollywood ran from the mid-1960s to the early 1980s, began with surprise hits (Bonnie and Clyde, The Graduate, Easy Rider); audiences drifting to television and drawn to foreign films; the film-school 'movie brats'; director-driven rejection of the studio system; Bonnie and Clyde's Godard- and Truffaut-inspired editing; the post-Jaws turn to blockbusters."),
    ("source.brit_bonnie_and_clyde_film", "Bonnie and Clyde (film by Penn)", "https://www.britannica.com/topic/Bonnie-and-Clyde-film-by-Penn", "Encyclopaedia Britannica",
     "Cited for: the 1967 film directed by Arthur Penn tore down barriers in the depiction of violence and sexuality."),
    ("source.tcm_bonnie_and_clyde_big_idea", "The Big Idea: Bonnie and Clyde", "https://www.tcm.com/articles/24135/the-big-idea-bonnie-and-clyde", "Turner Classic Movies",
     "Cited for: screenwriters David Newman and Robert Benton loved the work of Truffaut and Godard; Truffaut, their first choice, passed and suggested Godard, who also declined."),
    ("source.brit_heavens_gate_film", "Heaven's Gate (1980 film)", "https://www.britannica.com/topic/Heavens-Gate-film-by-Cimino", "Encyclopaedia Britannica",
     "Cited for: Cimino's Western exceeded an already colossal budget by nearly four times, was proportionately one of the biggest failures in movie history, hurt United Artists and ended most studios' interest in reviving the Western."),
    ("source.brit_jaws_film", "Jaws (film by Spielberg)", "https://www.britannica.com/topic/Jaws-film-by-Spielberg", "Encyclopaedia Britannica",
     "Cited for: released June 20, 1975, from Benchley's 1974 novel; opened in more than 400 US theaters; 30-second TV trailers the week before; films usually opened city by city; summer had been for lesser films; the first summer blockbuster, whose marketing became standard."),
    ("source.oyez_sony_v_universal", "Sony Corporation of America v. Universal City Studios, Inc.", "https://www.oyez.org/cases/1982/81-1687", "Oyez",
     "Cited for: Universal sued Sony over the Betamax; decided January 17, 1984, 5 to 4, opinion by Justice Stevens; selling VTRs is not contributory infringement; time-shifting; substantial noninfringing uses."),
    ("source.ebsco_home_video_rentals", "Home video rentals (Research Starters)", "https://www.ebsco.com/research-starters/film/home-video-rentals", "EBSCO",
     "Cited for: studios at first resisted the VCR as they had resisted television; prerecorded tapes often cost $100 or more, so people rented for around five dollars; by 1983 most studios sold tapes to rental stores and home users; rentals became a significant share of a film's revenue and Hollywood planned budgets around them."),
    ("source.brit_independent_film", "Independent film", "https://www.britannica.com/art/independent-film", "Encyclopaedia Britannica",
     "Cited for: independent film refers to films produced outside the major film studio system."),
    ("source.brit_cassavetes", "John Cassavetes", "https://www.britannica.com/biography/John-Cassavetes", "Encyclopaedia Britannica",
     "Cited for: Shadows was financed partly by donations after a radio appeal, shot on 16-mm film over about two and a half years, semi-improvised, and is generally acknowledged to have inaugurated the American independent movement; his acting paid for later films the studios would not back."),
    ("source.brit_night_of_the_living_dead", "Night of the Living Dead", "https://www.britannica.com/topic/Night-of-the-Living-Dead", "Encyclopaedia Britannica",
     "Cited for: the 1968 low-budget film was rejected by major studios but became a cult favourite, and set the pattern for modern zombie movies with contemporary settings."),
    ("source.brit_romero", "George A. Romero", "https://www.britannica.com/biography/George-A-Romero", "Encyclopaedia Britannica",
     "Cited for: Romero and several friends pooled their money to finance his first feature, Night of the Living Dead."),
    ("source.brit_sundance_festival", "Sundance Film Festival", "https://www.britannica.com/topic/Sundance-Film-Festival", "Encyclopaedia Britannica",
     "Cited for: began in 1978 in Salt Lake City as the Utah/United States Film Festival; came under Redford's Sundance Institute, founded to nurture independent filmmakers; named Sundance Film Festival in 1991; jump-started the Coen brothers, Soderbergh and Tarantino."),
    ("source.brit_mpt_special_effects", "Motion-picture technology: Special effects", "https://www.britannica.com/technology/motion-picture-technology/Special-effects", "Encyclopaedia Britannica",
     "Cited for: miniatures are relatively inexpensive and easy to handle and may be filmed faster than 24 frames per second; silent-era glass shots photographed actors through a pane of glass with a painted background."),
    ("source.uh_engines_matte_painting", "No. 3105: Matte Painting", "https://engines.egr.uh.edu/episode/3105", "University of Houston, The Engines of Our Ingenuity",
     "Cited for: matte painting is attributed to Norman Dawn's 1907 Missions of California; backgrounds painted on glass with unpainted parts, action filmed through them; The Wizard of Oz's distant Emerald City and Gone With the Wind's backdrops."),
    ("source.nfi_forced_perspective", "Forced Perspective", "https://www.nfi.edu/forced-perspective/", "Nashville Film Institute",
     "Cited for: forced perspective makes objects look larger, smaller, nearer or farther than they are; the closer something is to the camera, the larger it looks."),
    ("source.brit_king_kong_1933", "King Kong (film, 1933)", "https://www.britannica.com/topic/King-Kong-film-1933", "Encyclopaedia Britannica",
     "Cited for: directed by Cooper and Schoedsack; Willis O'Brien's stop-motion, miniature rear projection and traveling mattes; an 18-inch puppet plus giant arms, hands and feet; the first significant feature to star an animated character."),
    ("source.brit_harryhausen", "Ray Harryhausen", "https://www.britannica.com/biography/Ray-Harryhausen", "Encyclopaedia Britannica",
     "Cited for: stop-motion photographs objects in slightly different positions; after seeing King Kong he made stop-motion shorts in his parents' garage and later worked with Willis O'Brien."),
    ("source.brit_snow_white_1937", "Snow White and the Seven Dwarfs (film, 1937)", "https://www.britannica.com/topic/Snow-White-and-the-Seven-Dwarfs-film-1937", "Encyclopaedia Britannica",
     "Cited for: the first full-length animated feature from an American studio; Disney's biggest gamble to date; hundreds of technicians; 'Disney's Folly'; an immediate box-office sensation that set the standard for later Disney features."),
    ("source.aic_barbagallo_disney_cels", "Mickey, Donald, Goofy & Pluto: What's Breaking Up That Old Gang of Mine? (Barbagallo, Topics in Photographic Preservation, 1995)", "https://resources.culturalheritage.org/pmgtopics/1995-volume-six/06_06_Barbagallo.html", "American Institute for Conservation, Photographic Materials Group",
     "Cited for: a cel is a line drawing on a sheet of cellulose acetate, painted on the reverse; cels are registered in succession over painted backgrounds and photographed; Earl Hurd's December 19, 1914 patent application for transparent sheets over a background."),
    ("source.encyclopedia_com_bray", "John Randolph Bray (Encyclopedia of World Biography)", "https://www.encyclopedia.com/history/encyclopedias-almanacs-transcripts-and-maps/john-randolph-bray", "Encyclopedia.com",
     "Cited for: Hurd's 1914 cel process drew characters on transparent celluloid sheets laid over painted backgrounds, so only the moving parts had to be drawn."),
    ("source.brit_toy_story", "Toy Story (film, 1995)", "https://www.britannica.com/topic/Toy-Story", "Encyclopaedia Britannica",
     "Cited for: the first entirely computer-animated feature-length film, directed by John Lasseter, made by Pixar with Disney; 114,240 frames and 800,000 machine hours to render."),
    ("source.brit_computer_animation", "Computer animation", "https://www.britannica.com/topic/computer-animation", "Encyclopaedia Britannica",
     "Cited for: a digitized three-dimensional figure lets a computer generate a sequence of images that seem to move it through space; computers can supply in-between drawings."),
    ("source.brit_computer_graphics", "Computer graphics", "https://www.britannica.com/topic/computer-graphics", "Encyclopaedia Britannica",
     "Cited for: 3D models such as the Utah Teapot are built from many small polygons and can be shown as a wire frame."),
    ("source.brit_computer_graphics_shading", "Computer graphics: Shading and texturing", "https://www.britannica.com/topic/computer-graphics/Shading-and-texturing", "Encyclopaedia Britannica",
     "Cited for: Phong shading accounts for texture and all light sources at each pixel; ray tracing follows imaginary rays of light using the laws of reflection and refraction."),
    ("source.brit_scorsese_film_preservation", "Film Preservation: A Dire Need (essay by Martin Scorsese)", "https://www.britannica.com/art/Film-Preservation-A-Dire-Need-2119175", "Encyclopaedia Britannica",
     "Cited for: (2018) almost all pictures are shot digitally and finished digitally; theaters usually show a Digital Cinema Package sent over the internet or on a drive; digital restoration repairs damaged frames; digital information sometimes disappears, so files must be migrated; film is still the most reliable means of preserving movies."),
    ("source.loc_digitalpreservation_ampas", "The Academy of Motion Picture Arts and Sciences (Digital Preservation Pioneers)", "https://www.digitalpreservation.gov/series/pioneers/ampas.html", "Library of Congress",
     "Cited for: the Academy's 2007 report The Digital Dilemma found no digital archival master format or process with longevity equivalent to film."),
    ("source.ebsco_cinematography", "Cinematography (Research Starters)", "https://www.ebsco.com/research-starters/film/cinematography", "EBSCO",
     "Cited for: digital cinematography began to take off in the 1990s and was dominant by the mid-2010s; many advocates argue film has far superior visual quality."),
    ("source.brit_pixar", "Pixar Animation Studios", "https://www.britannica.com/topic/Pixar-Animation-Studios", "Encyclopaedia Britannica",
     "Cited for: Ed Catmull led Lucasfilm's computer division from 1979; spun off in 1986 under Steve Jobs's control; 1991 agreement with Disney for three computer-animated features; Toy Story in 1995."),
]

# Corroboration records: factId -> (evidence, [urls])
