// Generated by `npm run content:build`. Do not edit.
import type { Level } from '@brainscroll/core';

/** Each skill's lessons without the answer key, evaluated on first use (a require inside a function runs only when called). */
export const SKILL_LEVELS: Record<string, () => Level[]> = {
  'skill.arts.art_history': () => require('./art_history.json') as Level[],
  'skill.geography.world_geography': () => require('./world_geography.json') as Level[],
  'skill.history.ancient_rome': () => require('./ancient_rome.json') as Level[],
  'skill.money.how_money_works': () => require('./how_money_works.json') as Level[],
  'skill.science.astronomy': () => require('./astronomy.json') as Level[],
  'skill.world_systems.everyday_technology': () => require('./everyday_technology.json') as Level[],
  'skill.arts.music': () => require('./music.json') as Level[],
  'skill.geography.oceans': () => require('./oceans.json') as Level[],
  'skill.history.middle_ages': () => require('./middle_ages.json') as Level[],
  'skill.science.human_body': () => require('./human_body.json') as Level[],
  'skill.world_systems.government': () => require('./government.json') as Level[],
  'skill.arts.architecture': () => require('./architecture.json') as Level[],
  'skill.history.ancient_egypt': () => require('./ancient_egypt.json') as Level[],
  'skill.science.animals': () => require('./animals.json') as Level[],
  'skill.history.ancient_greece': () => require('./ancient_greece.json') as Level[],
  'skill.science.chemistry': () => require('./chemistry.json') as Level[],
};
