/**
 * Reviewed mappings from imported ingredient names to catalog IDs (scripts/import only).
 *
 * Keys are normalized names (lowercase, no punctuation; see normalizeText). Values:
 *  - a catalog ID, or several when one source line names two things ("salt and pepper");
 *  - `null`: a real ingredient with no catalog entry yet. Recipes that need it stay blocked
 *    and the import report counts how many recipes each one would unlock.
 *  - `'=other name'`: the same thing as another key (spelling variants), so the report counts them together.
 *  - `false`: not an ingredient at all (equipment listed under Ingredients); the line is dropped.
 *
 * Same rules as the catalog (docs/ingredient-mappings.md): same food in another form or
 * name only. Never map a substitution (bouillon is not broth, cayenne is not chili powder,
 * tomato sauce is not tomatoes). When unsure, use null and decide in the catalog.
 */
export const INGREDIENT_MAP: Record<string, string | string[] | null | false> = {
  // ── Two catalog items on one line ──
  'salt and pepper': ['salt', 'black_pepper'],
  'salt and black pepper': ['salt', 'black_pepper'],
  'salt pepper': ['salt', 'black_pepper'],

  // ── Same food, other wording ──
  'all purpose flour': 'flour',
  'ap flour': 'flour',
  'white flour': 'flour',
  'unsalted butter': 'butter',
  'salted butter': 'butter',
  'extra virgin olive oil': 'olive_oil',
  evoo: 'olive_oil',
  oil: 'vegetable_oil',
  'cooking oil': 'vegetable_oil',
  'sunflower oil': 'vegetable_oil',
  'rapeseed oil': 'vegetable_oil',
  'egg yolk': 'eggs',
  'egg yolks': 'eggs',
  'egg white': 'eggs',
  'egg whites': 'eggs',
  'yellow onions': 'onion',
  'red onions': 'onion',
  'white onions': 'onion',
  'clove garlic': 'garlic',
  'cloves garlic': 'garlic',
  'cloves of garlic': 'garlic',
  'clove of garlic': 'garlic',
  'garlic minced': 'garlic',
  'lemon juice': 'lemon',
  'juice of 1 lemon': 'lemon',
  'lemon zest': 'lemon',
  'lime juice': 'lime',
  'lime zest': 'lime',
  'ground black pepper': 'black_pepper',
  'sea salt': 'salt',
  'table salt': 'salt',
  'fine salt': 'salt',
  'caster sugar': 'sugar',
  'light brown sugar': 'brown_sugar',
  'dark brown sugar': 'brown_sugar',
  'chicken stock': 'chicken_broth',
  'vegetable stock': 'vegetable_broth',
  'grated parmesan': 'parmesan',
  'parmigiano reggiano': 'parmesan',
  'sharp cheddar': 'cheddar',
  'shredded cheddar': 'cheddar',
  'cooked rice': 'rice',
  'long grain rice': 'rice',
  'basmati rice': 'rice',
  'beef mince': 'ground_beef',
  'minced meat': null, // beef, pork or a mix: the recipe must say which
  'whipping cream': 'heavy_cream',
  'heavy whipping cream': 'heavy_cream',
  'pure vanilla extract': 'vanilla',
  'vanilla essence': 'vanilla',
  'old fashioned rolled oats': 'oats',
  'spring onion': 'green_onion',
  'wheat flour': 'flour', // European usage: plain flour. Whole wheat is separate.
  'plain flour': 'flour',
  'basil leaves': 'basil',
  'fresh basil leaves': 'basil',
  'jalapeno pepper': 'jalapeno',
  'jalapeno peppers': 'jalapeno',
  'green bell pepper': 'bell_pepper',
  'red bell pepper': 'bell_pepper',
  'yellow bell pepper': 'bell_pepper',
  'ground beef meat': 'ground_beef',
  'lean ground beef': 'ground_beef',
  'light soy sauce': 'soy_sauce',
  'low sodium soy sauce': 'soy_sauce',
  'warm water': 'water',
  'lukewarm water': 'water',
  'hot water': 'water',
  'cold water': 'water',
  'boiling water': 'water',
  'ice water': 'water',
  'coarse salt': 'salt',
  'fine sea salt': 'salt',
  'dry oregano': 'oregano',
  'cinnamon powder': 'cinnamon',
  'paprika powder': 'paprika',
  'sweet paprika': 'paprika',
  'cooked chickpeas': 'chickpeas',
  'canned chickpeas': 'chickpeas',
  'butter or margarine': 'butter',
  'lard or butter': 'butter',
  'butter or lard': 'butter',
  'bacon strips': 'bacon',
  'rashers of bacon': 'bacon',
  'bacon rashers': 'bacon',
  'sweet butter': 'butter', // old name for unsalted butter
  oranges: '=orange',
  orange: null,
  'maple syrup': null,
  thermos: false,
  'whole milk': 'milk',
  'cold whole milk': 'milk',
  'frozen spinach': null, // cooks differently from fresh; decide in the catalog

  // ── Spelling variants of one missing ingredient (counted together in the report) ──
  'bay leaves': '=bay leaf',
  bayleaf: '=bay leaf',
  'bay leaf': null,
  'ground nutmeg': '=nutmeg',
  nutmeg: null,
  cayenne: '=cayenne pepper',
  'powdered sugar': null,
  'icing sugar': '=powdered sugar',
  'confectioners sugar': '=powdered sugar',
  'powdered white sugar': '=powdered sugar',
  cornstarch: null,
  cornflour: '=cornstarch', // UK name for cornstarch
  'corn starch': '=cornstarch',
  'active dry yeast': null,
  'dry yeast': '=active dry yeast',
  'instant yeast': null,
  yogurt: null,
  'plain yogurt': '=yogurt',
  'natural yogurt': '=yogurt',
  leek: null,
  leeks: '=leek',
  coriander: null, // leaves (cilantro) or seed: the recipe must say
  'ground coriander': null,
  'dill weed': '=dill',
  dill: null,
  'panko breadcrumbs': '=bread crumbs',
  panko: '=bread crumbs',
  chilli: '=chili pepper',
  'chilli pepper': '=chili pepper',
  'chili pepper': null,
  cheese: null, // which cheese? The editor names it or the recipe stays out

  // ── Not ingredients ──
  thermometer: false,
  cheesecloth: false,
  'cheese recipient': false,
  'kitchen twine': false,
  'parchment paper': false,
  'baking paper': false,
  toothpicks: false,
  skewers: false,

  // ── Kept out on purpose (look alike, different food) ──
  'rice vinegar': null,
  'tomato sauce': null,
  'chicken bouillon': null,
  'bouillon cube': null,
  'cayenne pepper': null,
  'pepper jack': null,
  'bread crumbs': null,
  breadcrumbs: '=bread crumbs',
  peanuts: null,
  'butternut squash': null,
  peppercorns: null, // whole, not ground pepper
  'black peppercorns': '=peppercorns',
  'cumin seeds': null, // whole, not ground cumin
  'cinnamon sticks': null,
  'dried basil': null, // the catalog's basil is fresh
  'dark soy sauce': null,
  'condensed milk': null,
  'sweetened condensed milk': '=condensed milk',
  'evaporated milk': null,
  'tomato puree': null,
  'bomba rice': null,
  'whole wheat flour': null,
  'bread flour': null,
  beef: null, // which cut?
  vinegar: null,
  buttermilk: null,
  'coconut cream': null,
  'cream of tartar': null,
  'onion powder': null,
  'garlic salt': null,
  'brown rice': null,
  'arborio rice': null, // risotto needs it; plain long-grain won't work
  'sweet potato noodles': null,
  'lemon pepper': null,
};
