// Generated by `npm run art:sync` from app/assets/images/art/. Don't edit by hand.
import type { ImageSourcePropType } from 'react-native';

export const ART: Record<string, ImageSourcePropType> = {
};
