import type { ImageSourcePropType } from 'react-native';

/**
 * Profile avatars (owner art, 2026-10-01; briefs in docs/images-avatars*.md):
 * one per tree, all unlocked from the start, and a gold one per tree for
 * mastering it (core avatarUnlocked). Keyed by avatar id: `avatar.<skill
 * slug>` and `avatar.<skill slug>.gold`. React Native needs a literal
 * require() for each file.
 */
export const AVATAR_ART: Record<string, ImageSourcePropType> = {
  'avatar.ancient_egypt.gold': require('../../../assets/images/avatars/ancient_egypt-gold.webp'),
  'avatar.ancient_egypt': require('../../../assets/images/avatars/ancient_egypt.webp'),
  'avatar.ancient_greece.gold': require('../../../assets/images/avatars/ancient_greece-gold.webp'),
  'avatar.ancient_greece': require('../../../assets/images/avatars/ancient_greece.webp'),
  'avatar.ancient_rome.gold': require('../../../assets/images/avatars/ancient_rome-gold.webp'),
  'avatar.ancient_rome': require('../../../assets/images/avatars/ancient_rome.webp'),
  'avatar.animals.gold': require('../../../assets/images/avatars/animals-gold.webp'),
  'avatar.animals': require('../../../assets/images/avatars/animals.webp'),
  'avatar.architecture.gold': require('../../../assets/images/avatars/architecture-gold.webp'),
  'avatar.architecture': require('../../../assets/images/avatars/architecture.webp'),
  'avatar.art_history.gold': require('../../../assets/images/avatars/art_history-gold.webp'),
  'avatar.art_history': require('../../../assets/images/avatars/art_history.webp'),
  'avatar.astronomy.gold': require('../../../assets/images/avatars/astronomy-gold.webp'),
  'avatar.astronomy': require('../../../assets/images/avatars/astronomy.webp'),
  'avatar.chemistry.gold': require('../../../assets/images/avatars/chemistry-gold.webp'),
  'avatar.chemistry': require('../../../assets/images/avatars/chemistry.webp'),
  'avatar.computers.gold': require('../../../assets/images/avatars/computers-gold.webp'),
  'avatar.computers': require('../../../assets/images/avatars/computers.webp'),
  'avatar.earth_climate.gold': require('../../../assets/images/avatars/earth_climate-gold.webp'),
  'avatar.earth_climate': require('../../../assets/images/avatars/earth_climate.webp'),
  'avatar.everyday_technology.gold': require('../../../assets/images/avatars/everyday_technology-gold.webp'),
  'avatar.everyday_technology': require('../../../assets/images/avatars/everyday_technology.webp'),
  'avatar.film_tv.gold': require('../../../assets/images/avatars/film_tv-gold.webp'),
  'avatar.film_tv': require('../../../assets/images/avatars/film_tv.webp'),
  'avatar.government.gold': require('../../../assets/images/avatars/government-gold.webp'),
  'avatar.government': require('../../../assets/images/avatars/government.webp'),
  'avatar.how_money_works.gold': require('../../../assets/images/avatars/how_money_works-gold.webp'),
  'avatar.how_money_works': require('../../../assets/images/avatars/how_money_works.webp'),
  'avatar.human_body.gold': require('../../../assets/images/avatars/human_body-gold.webp'),
  'avatar.human_body': require('../../../assets/images/avatars/human_body.webp'),
  'avatar.literature.gold': require('../../../assets/images/avatars/literature-gold.webp'),
  'avatar.literature': require('../../../assets/images/avatars/literature.webp'),
  'avatar.logic.gold': require('../../../assets/images/avatars/logic-gold.webp'),
  'avatar.logic': require('../../../assets/images/avatars/logic.webp'),
  'avatar.middle_ages.gold': require('../../../assets/images/avatars/middle_ages-gold.webp'),
  'avatar.middle_ages': require('../../../assets/images/avatars/middle_ages.webp'),
  'avatar.music.gold': require('../../../assets/images/avatars/music-gold.webp'),
  'avatar.music': require('../../../assets/images/avatars/music.webp'),
  'avatar.oceans.gold': require('../../../assets/images/avatars/oceans-gold.webp'),
  'avatar.oceans': require('../../../assets/images/avatars/oceans.webp'),
  'avatar.philosophy.gold': require('../../../assets/images/avatars/philosophy-gold.webp'),
  'avatar.philosophy': require('../../../assets/images/avatars/philosophy.webp'),
  'avatar.probability.gold': require('../../../assets/images/avatars/probability-gold.webp'),
  'avatar.probability': require('../../../assets/images/avatars/probability.webp'),
  'avatar.psychology.gold': require('../../../assets/images/avatars/psychology-gold.webp'),
  'avatar.psychology': require('../../../assets/images/avatars/psychology.webp'),
  'avatar.religions.gold': require('../../../assets/images/avatars/religions-gold.webp'),
  'avatar.religions': require('../../../assets/images/avatars/religions.webp'),
  'avatar.us_history.gold': require('../../../assets/images/avatars/us_history-gold.webp'),
  'avatar.us_history': require('../../../assets/images/avatars/us_history.webp'),
  'avatar.world_geography.gold': require('../../../assets/images/avatars/world_geography-gold.webp'),
  'avatar.world_geography': require('../../../assets/images/avatars/world_geography.webp'),
};
