def wk(t):
    return "https://en.wikipedia.org/wiki/" + t

def F(id, text, sources, cards, evidence, urls):
    return {"id": "fact.film_tv." + id, "text": text, "sourceIds": sources, "cardIds": cards,
            "_evidence": evidence, "_urls": urls}

def C(id, title, desc, diff, facts):
    return {"id": "concept.film_tv." + id, "title": title, "description": desc, "difficulty": diff, "facts": facts}

c = lambda lvl, n: f"card.film_tv.{lvl:03d}.c{n}"

CONCEPTS = [
    # ── Level 71 ──
    C("tv_born_from_radio", "Television grew out of radio's networks",
      "American TV borrowed radio's networks: NBC's 1926 radio chain, its Blue network that became ABC, and NBC's own TV network by 1948.", 0.3, [
        F("tv_radio_with_pictures", "Television was first regarded by many as 'radio with pictures.'",
          ["source.brit_tv_us_overview"], [c(71, 1)],
          "Golden Globes feature 'Radio with Pictures: The Rise of Television' and a 2010 history column both describe early TV as radio with pictures.",
          ["https://goldenglobes.com/articles/radio-pictures-rise-television/", "https://bill37mccurdy.com/2010/08/20/early-tv-was-like-radio-with-pictures/"]),
        F("tv_radio_still_bigger_1948", "In 1948 television was still in its experimental stage, and radio remained the number one broadcast medium.",
          ["source.brit_tv_us_overview"], [c(71, 1)],
          "Wikipedia (Golden Age of Television): shows such as The Jack Benny Program ran on both radio and TV until TV reception reached beyond the big cities in the mid-1950s; at the start of 1948 only about 175,000 US homes had TV.",
          [wk("Golden_Age_of_Television"), "http://www.jimramsburg.com/the-1948-49-season.html"]),
        F("tv_nbc_radio_network_1926", "NBC was formed in 1926; on November 15, 1926, 25 radio stations in 21 cities carried its first network program from New York.",
          ["source.loc_nbc_guide"], [c(71, 2), c(80, 3)],
          "Wikipedia (NBC): formed in 1926 by RCA as the first major US broadcast network; the Radio Historian's NBC gallery and CultureNow describe the November 15, 1926 Waldorf-Astoria broadcast carried by 25 stations in 21 cities.",
          [wk("NBC"), "http://www.theradiohistorian.org/nbcgallery/nbcgallery1.html", "https://culturenow.org/site/nbcs-1st-broadcast"]),
        F("tv_nbc_blue_becomes_abc", "After the FCC refused licenses to companies running more than one network, NBC was forced to sell its Blue radio network, which became ABC.",
          ["source.loc_nbc_guide"], [c(71, 2)],
          "Wikipedia (Blue Network): the Blue Network was divested from NBC in 1942 after antitrust action and formally became the American Broadcasting Company in 1945.",
          [wk("Blue_Network"), wk("American_Broadcasting_Company")]),
        F("tv_nbc_tv_47_stations_1948", "NBC began operating its first television station in 1939, and by 1948 its TV network had 47 stations.",
          ["source.loc_nbc_guide"], [c(71, 2)],
          "Wikipedia (NBC): originally a radio network, NBC pioneered commercial television in 1939; a 1948-49 season history counts the number of operating TV stations growing to 47 in 1948.",
          [wk("NBC"), "http://www.jimramsburg.com/the-1948-49-season.html"]),
    ]),
    C("tv_radio_stars_and_sponsors", "Radio's stars and sponsors came to TV",
      "Radio stars hesitated, then followed Milton Berle into TV; CBS lured NBC's radio stars in 1948; and advertising, radio's way of paying, became TV's too.", 0.3, [
        F("tv_radio_stars_reluctant", "Most of radio's biggest stars, such as Jack Benny, Bob Hope, and George Burns and Gracie Allen, were at first reluctant to risk their careers on television.",
          ["source.brit_tv_us_overview"], [c(71, 3)],
          "Wikipedia (Golden Age of Television): radio and TV versions of shows such as The Jack Benny Program ran side by side into the mid-1950s; Golden Globes history of early TV notes radio stars' caution about the new medium.",
          [wk("Golden_Age_of_Television"), "https://goldenglobes.com/articles/radio-pictures-rise-television/"]),
        F("tv_berle_texaco_first_hit", "Milton Berle, who had had little success on radio, starred in NBC's Texaco Star Theatre from 1948; it was TV's first hit and led to a dramatic increase in TV set sales, earning him the name Mr. Television.",
          ["source.brit_tv_us_overview", "source.brit_texaco_star_theatre"], [c(71, 3)],
          "Wikipedia (Texaco Star Theater; Milton Berle): the TV version began on NBC on June 8, 1948, was one of the first successful US TV shows, helped propel TV set sales and gave Berle the nickname Mr. Television.",
          [wk("Texaco_Star_Theater"), wk("Milton_Berle")]),
        F("tv_homes_2_to_70_percent", "When Texaco Star Theatre debuted in 1948, fewer than 2 percent of US homes had a TV set; by 1956, TV was in 70 percent of homes.",
          ["source.brit_tv_us_overview", "source.brit_texaco_star_theatre"], [c(71, 3)],
          "A 1948-49 season history counts about 175,000 TV homes at the start of 1948 (well under 2 percent of US households); Macmillan's Media and Culture puts TV in about 9 percent of homes in 1950 and 55 percent by 1954, consistent with 70 percent by 1956.",
          ["http://www.jimramsburg.com/the-1948-49-season.html", "https://www.macmillanhighered.com/BrainHoney/Resource/6700/digital_first_content/trunk/test/mediaculture10eupdate/mediaculture10eupdate_ch6_2.html"]),
        F("tv_cbs_talent_raid_1948", "In 1948 CBS chief William S. Paley signed radio stars away from NBC, including Jack Benny, George Burns and Gracie Allen, and Amos 'n' Andy's creators; they proved as popular on TV as on radio.",
          ["source.brit_cbs"], [c(71, 4), c(80, 4)],
          "Wikipedia (Jack Benny): Benny's show moved to CBS in January 1949 as part of William S. Paley's 'raid' on NBC talent in 1948 to 1949, and later ran on CBS television.",
          [wk("Jack_Benny"), wk("William_S._Paley")]),
        F("tv_cbs_radio_origin", "CBS began as a radio network in the late 1920s and grew under William S. Paley.",
          ["source.brit_cbs"], [c(71, 4)],
          "Wikipedia (CBS): founded as United Independent Broadcasters in 1927, it became the Columbia Broadcasting System, with William S. Paley in charge from 1928.",
          [wk("CBS")]),
        F("tv_ads_pay_broadcasting", "Advertising became the principal means of support for broadcasting in the United States; sponsored network programs furnished revenue to both the network and its stations.",
          ["source.brit_broadcasting"], [c(71, 5), c(76, 1)],
          "Wikipedia (Television advertisement; Golden Age of Television): US radio and early TV programs were paid for by advertisers, often a single sponsor per show.",
          [wk("Television_advertisement"), wk("Golden_Age_of_Television")]),
        F("tv_sponsors_moved_hits", "On NBC radio, breakout hits on the Blue network were often moved to the more popular Red network at the request of sponsors.",
          ["source.loc_nbc_guide"], [c(71, 5)],
          "Wikipedia (Blue Network): the Red network carried the more commercially successful, sponsored programs, and popular shows moved from Blue to Red.",
          [wk("Blue_Network")]),
    ]),
    # ── Level 72 ──
    C("tv_big_three_networks", "Three networks ruled prime time",
      "Four networks started regular schedules in 1948; DuMont folded, and ABC, CBS and NBC held more than 90 percent of the prime-time audience in the late 1970s.", 0.3, [
        F("tv_four_networks_1948", "Regular programming on the four networks, ABC, CBS, NBC and DuMont, was scarce until the fall of 1948; DuMont folded in the mid-1950s.",
          ["source.brit_tv_us_overview"], [c(72, 2)],
          "Wikipedia (DuMont Television Network): an American network from 1946 to 1956 that by 1955 could no longer continue network operations; Wikipedia (1948 in American television) on regular network schedules from 1948.",
          [wk("DuMont_Television_Network"), wk("1948_in_American_television")]),
        F("tv_prime_time_hours", "Prime time is the evening block from 8 to 11 PM Eastern time.",
          ["source.brit_tv_us_overview"], [c(72, 2)],
          "Wikipedia (NBC): the network provides prime-time programming to affiliates from 8:00 to 11:00 p.m. Eastern and Pacific time.",
          [wk("NBC"), wk("Prime_time")]),
        F("tv_big_three_90_percent", "In the late 1970s, more than 90 percent of the US prime-time viewing audience watched ABC, CBS or NBC.",
          ["source.brit_tv_us_miniseries"], [c(72, 1), c(78, 3)],
          "Lumen Learning's Media and Culture (9.3) and Encyclopedia.com's 'Prime Time Audiences Gain More Choices' both give more than 90 percent of the prime-time audience for the three networks in the late 1970s.",
          ["https://courses.lumenlearning.com/suny-massmedia/chapter/9-3-issues-and-trends-in-the-television-industry/", "https://www.encyclopedia.com/arts/news-wires-white-papers-and-books/prime-time-audiences-gain-more-choices-1980s-2000s"]),
    ]),
    C("tv_shared_mass_culture", "The network era's shared screen",
      "With nearly every home tuned to the same three networks, TV became cultural glue: a big event like the 1960 debate reached most of the country at once.", 0.35, [
        F("tv_homes_90_percent_1960", "By 1960 nearly 90 percent of American homes had a television.",
          ["source.brit_tv_us_kennedy_nixon"], [c(72, 3)],
          "Macmillan's Media and Culture ('The Origins and Development of Television') puts TV in about 90 percent of US homes by 1960.",
          ["https://www.macmillanhighered.com/BrainHoney/Resource/6700/digital_first_content/trunk/test/mediaculture10eupdate/mediaculture10eupdate_ch6_2.html"]),
        F("tv_debate_1960_simulcast", "On September 26, 1960, the first televised presidential debate, between John F. Kennedy and Richard Nixon, was simulcast on all three networks and reached a then-record audience of about 70 million.",
          ["source.brit_tv_us_kennedy_nixon"], [c(72, 3)],
          "Wikipedia (1960 United States presidential debates) and the National Constitution Center: the September 26, 1960 debate was the first televised one, carried by the networks and watched by about 70 million Americans.",
          [wk("1960_United_States_presidential_debates"), "https://constitutioncenter.org/blog/the-debate-that-changed-the-world-of-politics"]),
        F("tv_cultural_glue", "Britannica calls radio and television a kind of cultural glue: from 1929 to 1989, nearly the entire country, young and old, rich and poor, fed from the same cultural trough.",
          ["source.brit_tv_us_1990s"], [c(72, 4)],
          "Wikipedia (Network era): the three networks, first established by radio, played a significant role in postwar American identity, and programming was strictly uniform.",
          [wk("Network_era")]),
        F("tv_three_company_mass_culture", "Control of television by three companies produced a unified mass culture whose products were experienced by nearly everyone.",
          ["source.brit_tv_us_1990s"], [c(72, 4), c(80, 4)],
          "Wikipedia (Network era; Big Three television networks): ABC, CBS and NBC dominated US television and its uniform programming until cable's rise.",
          [wk("Network_era"), wk("Big_Three_television_networks")]),
    ]),
    # ── Level 73 ──
    C("tv_live_anthology_drama", "Live TV drama and the anthology series",
      "Early network TV was mostly live; anthology series staged a new play each week, and writers such as Paddy Chayefsky and Rod Serling made their names.", 0.35, [
        F("tv_mostly_live_early_1950s", "In the early 1950s most network television was broadcast live; by the early 1960s most was recorded.",
          ["source.brit_tv_us_late_golden_age"], [c(73, 1), c(73, 4)],
          "Wikipedia (Golden Age of Television): filmed programming in prime time grew from about 20 percent in 1951 and 58 percent in 1956 to about 80 percent in 1961-62.",
          [wk("Golden_Age_of_Television")]),
        F("tv_anthology_dramas", "Most TV plays of the era were anthology dramas, weekly series presenting original and adapted plays under one title, such as Kraft Television Theatre (1947–58) and Studio One (1948–58).",
          ["source.brit_tv_us_early_genres"], [c(73, 2)],
          "Wikipedia (Anthology series): anthology series present a different story and cast each episode; its list includes Kraft Television Theatre (1947-58) and Studio One.",
          [wk("Anthology_series")]),
        F("tv_teleplay_writers", "Young writers such as Paddy Chayefsky, Rod Serling and Gore Vidal wrote highly regarded teleplays for the network anthology series.",
          ["source.brit_tv_us_early_genres"], [c(73, 2)],
          "Wikipedia (Golden Age of Television): the era's live anthology dramas drew writers including Paddy Chayefsky, Rod Serling and Gore Vidal.",
          [wk("Golden_Age_of_Television")]),
        F("tv_marty_1953_to_1955", "Marty began as a 1953 television play and became a 1955 film that won the Academy Award for best picture.",
          ["source.brit_tv_us_early_genres"], [c(73, 2)],
          "Wikipedia (Marty (teleplay); Marty (film)): Paddy Chayefsky's play was telecast live on May 24, 1953, and the 1955 film version won the Academy Award for Best Picture.",
          [wk("Marty_(teleplay)"), wk("Marty_(film)")]),
    ]),
    C("tv_kinescope_videotape", "From kinescope to videotape",
      "Before 1956, TV could be recorded only by filming a monitor (a kinescope), which was costly and poor; Ampex's videotape, and filmed Hollywood series, ended the live era.", 0.4, [
        F("tv_kinescope_method", "Before videotape, the only way to record TV was on film: a movie camera pointed at a TV monitor made a kinescope, which was developed and later projected for broadcast in other time zones.",
          ["source.ethw_ampex_vtr_1956", "source.tva_videotape_debut"], [c(73, 3)],
          "Wikipedia (Kinescope): a kinescope is a recording of a TV program on motion picture film through a lens focused on a video monitor, used for re-broadcasting before videotape.",
          [wk("Kinescope")]),
        F("tv_kinescope_costly", "Kinescope recordings were poor in quality and expensive, since the film could be used only once; by 1954 TV broadcasters were using more raw film than the entire movie industry.",
          ["source.ethw_ampex_vtr_1956"], [c(73, 3)],
          "Wikipedia (Kinescope): by 1954 the television industry's film consumption surpassed that of all the Hollywood studios combined.",
          [wk("Kinescope")]),
        F("tv_ampex_videotape_1956", "In 1956 Ampex introduced the first practical videotape recorder for TV stations and networks, replacing kinescope film.",
          ["source.ethw_ampex_vtr_1956"], [c(73, 4), c(80, 3)],
          "Wikipedia (Ampex): Ampex's quadruplex videotape recorder, introduced in 1956, became the broadcast standard.",
          [wk("Ampex"), wk("Quadruplex_videotape")]),
        F("tv_videotape_first_air_1956", "On November 30, 1956, CBS taped a live New York newscast on an Ampex recorder in Hollywood and rebroadcast it hours later to the West Coast.",
          ["source.tva_videotape_debut", "source.ethw_ampex_vtr_1956"], [c(73, 4)],
          "Wikipedia (Quadruplex videotape): the first on-air use of videotape was CBS's delayed broadcast of Douglas Edwards and the News on November 30, 1956.",
          [wk("Quadruplex_videotape")]),
        F("tv_filmed_shows_hollywood", "TV production moved to the Los Angeles area, the live theatrical style gave way to shows recorded on film, and filmed shows could earn income indefinitely from reruns.",
          ["source.brit_tv_us_late_golden_age"], [c(73, 4), c(80, 4)],
          "Wikipedia (Golden Age of Television): by the late 1950s production of most American television was moving from New York to Hollywood, and filmed programming grew.",
          [wk("Golden_Age_of_Television")]),
    ]),
    # ── Level 74 ──
    C("tv_sitcom_format", "What a sitcom is",
      "A situation comedy is a half-hour series with a continuing cast in the same setting, week after week; I Love Lucy grew from a radio comedy.", 0.3, [
        F("tv_sitcom_definition", "The sitcom was a 30-minute format featuring a continuing cast of characters that appeared in the same setting week after week.",
          ["source.brit_tv_us_sitcoms"], [c(74, 2)],
          "Wikipedia (Sitcom): a sitcom centers on a recurring cast of characters in a consistent setting, such as a home or workplace.",
          [wk("Sitcom")]),
        F("tv_lucy_debut_1951", "I Love Lucy (CBS, 1951–57), starring Lucille Ball and Desi Arnaz, debuted in October 1951; it was shot on film in Hollywood rather than broadcast live from New York.",
          ["source.brit_tv_us_sitcoms"], [c(74, 1), c(80, 3)],
          "Wikipedia (I Love Lucy): aired on CBS from October 15, 1951, to May 6, 1957, filmed by Desilu in Hollywood.",
          [wk("I_Love_Lucy")]),
        F("tv_lucy_from_radio", "I Love Lucy was adapted for TV from My Favorite Husband, a CBS radio comedy in which Lucille Ball starred from 1948.",
          ["source.loc_lucy_cast_crew_set", "source.loc_lcib_we_still_love_lucy"], [c(74, 2)],
          "Wikipedia (I Love Lucy): the series is based on My Favorite Husband, and many early scripts were rewrites from Ball's late-1940s radio show.",
          [wk("I_Love_Lucy"), wk("Golden_Age_of_Television")]),
        F("tv_lucy_setting", "I Love Lucy's early episodes took place mostly in a New York apartment building, where Lucy and Ricky Ricardo lived near their landlords and friends, Fred and Ethel Mertz.",
          ["source.loc_lucy_cast_crew_set"], [c(74, 2)],
          "Wikipedia (I Love Lucy): originally set in an apartment building in New York City, with the Mertzes as the Ricardos' landlords and friends.",
          [wk("I_Love_Lucy")]),
    ]),
    C("tv_three_camera_lucy", "I Love Lucy's three-camera method",
      "Filmed on 35 mm with three cameras before a live audience and edited on a four-headed Moviola, I Love Lucy set the sitcom standard and could be rerun.", 0.4, [
        F("tv_lucy_kinescope_cheesecloth", "Most TV shows were then made in the East, broadcast live there and shown to western time zones as kinescope copies, which a Library of Congress specialist likened to watching TV through a cheesecloth; Ball and Arnaz chose to produce their show in Hollywood.",
          ["source.loc_lcib_we_still_love_lucy"], [c(74, 1), c(74, 3)],
          "Television Academy Foundation ('50 Years Ago: Videotape Debuts'): West Coast viewers saw live eastern shows as fresh kinescopes; Wikipedia (Kinescope) on their poor picture quality.",
          ["https://interviews.televisionacademy.com/news/50-years-ago-videotape-debuts", wk("Kinescope")]),
        F("tv_lucy_three_cameras", "Cinematographer Karl Freund and director Marc Daniels are generally credited with filming I Love Lucy with three cameras in front of a live audience, the technique that became the standard for sitcoms.",
          ["source.loc_lucy_cast_crew_set"], [c(74, 3), c(80, 4)],
          "Wikipedia (Multiple-camera setup): Desi Arnaz, Al Simon and cinematographer Karl Freund used the multiple-camera setup to film I Love Lucy in 1951 (other producers had used it earlier).",
          [wk("Multiple-camera_setup"), wk("Karl_Freund")]),
        F("tv_lucy_35mm_live_audience", "I Love Lucy was shot on 35 mm film before a live audience, with one lighting system for the whole set.",
          ["source.loc_lcib_we_still_love_lucy"], [c(74, 3)],
          "Wikipedia (Dann Cahn): I Love Lucy shot with three cameras and delivered in 35 mm instead of kinescopes.",
          [wk("Dann_Cahn")]),
        F("tv_lucy_stage_play_moviola", "With three motion picture cameras, I Love Lucy could be filmed continuously and in sequence, like a stage play; editor Dann Cahn cut it on a Moviola with four heads, three for picture and one for sound.",
          ["source.deadline_dann_cahn"], [c(74, 3), c(74, 4)],
          "Wikipedia (Dann Cahn): Cahn was one of the first editors to master cutting on a film Moviola with four heads (three for picture and one for sound) for I Love Lucy.",
          [wk("Dann_Cahn")]),
        F("tv_lucy_reruns_1955", "Because it was produced on film, I Love Lucy could be shown again, and in 1955 it became one of the first series broadcast as reruns.",
          ["source.loc_lcib_we_still_love_lucy"], [c(74, 4)],
          "Wikipedia (I Love Lucy): beginning in April 1955 CBS added reruns of the show's early years to its schedule, an early step toward the rerun syndication market.",
          [wk("I_Love_Lucy")]),
    ]),
    # ── Level 75 ──
    C("tv_evening_news_half_hour", "The evening news grows to half an hour",
      "Network evening newscasts ran 15 minutes until 1963, when CBS under Walter Cronkite, and then the others, expanded to half an hour.", 0.3, [
        F("tv_news_15_to_30_1963", "In 1963 the network evening news programs expanded from 15 minutes to half an hour.",
          ["source.daedalus_mandelbaum_tv_war", "source.brit_walter_cronkite"], [c(75, 1), c(75, 2), c(80, 2)],
          "Wikipedia (CBS Evening News): its running time was 15 minutes from 1941 to 1963 and 30 minutes from 1963.",
          [wk("CBS_Evening_News")]),
        F("tv_cronkite_first_half_hour", "Walter Cronkite became anchor of the CBS evening news in 1962; soon after, its 15 minutes became 30, the first half-hour nightly news show on American network television.",
          ["source.brit_walter_cronkite"], [c(75, 2)],
          "Wikipedia (CBS Evening News; Walter Cronkite): Cronkite took over the broadcast in 1962 and it expanded to 30 minutes in September 1963.",
          [wk("CBS_Evening_News"), wk("Walter_Cronkite")]),
    ]),
    C("tv_vietnam_television_war", "Vietnam, the first television war",
      "Vietnam was the first televised war: evening news showed film, flown in by air, of planes and patrols, and in 1968 Cronkite went to see for himself.", 0.4, [
        F("tv_vietnam_first_televised", "The Vietnam War was the first war to be televised; Americans regularly saw film of airplanes flying, often dropping bombs, and troops on patrol, sometimes in combat.",
          ["source.daedalus_mandelbaum_tv_war"], [c(75, 3)],
          "American Foreign Relations encyclopedia ('The first television war') and the Encyclopedia of TV & Radio ('Vietnam on Television') describe Vietnam as the first war brought nightly into American homes by TV news film.",
          ["https://www.americanforeignrelations.com/O-W/Television-The-first-television-war.html", "https://www.tvencyclopedia.org/tv-encyclopedia-17/vietnam-on-television"]),
        F("tv_vietnam_film_by_air", "Film of the Vietnam War usually reached the networks as cans of film shipped by air.",
          ["source.daedalus_mandelbaum_tv_war"], [c(75, 3)],
          "Encyclopedia of TV & Radio ('Vietnam on Television'): film reports had to be flown to the United States for processing and broadcast, so they were typically days old.",
          ["https://www.tvencyclopedia.org/tv-encyclopedia-17/vietnam-on-television"]),
        F("tv_cronkite_tet_1968", "In 1968 Walter Cronkite left the anchor desk to report from Vietnam after the Tet Offensive and declared that the war could end only in a stalemate.",
          ["source.brit_walter_cronkite"], [c(75, 4)],
          "Wikipedia (Walter Cronkite): in February 1968 Cronkite traveled to Vietnam to cover the aftermath of the Tet Offensive and on his return said the war was mired in stalemate.",
          [wk("Walter_Cronkite")]),
    ]),
    # ── Level 76 ──
    C("tv_sponsors_to_spots", "From single sponsors to commercials",
      "After the rigged quiz shows of the late 1950s, networks took shows away from single sponsors and sold short commercial slots, like ad pages in a magazine.", 0.35, [
        F("tv_quiz_shows_rigged", "In 1958 former contestants revealed that big-money TV quiz shows were rigged and contestants coached; a House subcommittee held hearings in 1959.",
          ["source.tva_quiz_show_scandals"], [c(76, 2)],
          "Wikipedia (1950s quiz show scandals): contestants were secretly assisted to arrange outcomes; Congress investigated the scandals.",
          [wk("1950s_quiz_show_scandals")]),
        F("tv_single_sponsorship_ends", "After the quiz show scandals, networks grew wary of single-sponsor programs and sold advertising time in 15-, 30- and 60-second units, taking control from sponsors and ad agencies.",
          ["source.tva_quiz_show_scandals", "source.pbs_amex_quiz_aftermath"], [c(76, 2)],
          "Encyclopedia.com ('Quiz Show Scandals') and Lumen Learning's Media and Culture (9.3): after the scandals, networks ended the single-sponsor format and moved to multiple advertisers buying commercials.",
          ["https://www.encyclopedia.com/media/encyclopedias-almanacs-transcripts-and-maps/quiz-show-scandals", "https://courses.lumenlearning.com/suny-massmedia/chapter/9-3-issues-and-trends-in-the-television-industry/"]),
        F("tv_producers_control_magazine_model", "Producers took full control of shows and stations sold commercial time, following the model of magazines and newspapers; removing advertisers from the shows removed their urge to interfere with content.",
          ["source.pbs_amex_quiz_aftermath"], [c(76, 2)],
          "Wikipedia (Pat Weaver): NBC's Pat Weaver developed the magazine style of advertising, in which sponsors bought one- or two-minute blocks rather than whole shows.",
          [wk("Pat_Weaver"), "https://courses.lumenlearning.com/suny-massmedia/chapter/9-3-issues-and-trends-in-the-television-industry/"]),
    ]),
    C("tv_nielsen_ratings", "Nielsen ratings price the audience",
      "From 1950 Nielsen measured viewing in a sample of homes with Audimeters and diaries; ratings and shares set what advertising on each program costs.", 0.4, [
        F("tv_nielsen_audimeter_1950", "From 1950 A.C. Nielsen rated TV shows using a sample of more than 1,000 TV homes; each had a small box, the Audimeter, attached to the set to record when it was on and what channel it was tuned to, and a smaller group kept viewing diaries.",
          ["source.brit_ac_nielsen"], [c(76, 3)],
          "Wikipedia (Nielsen ratings): Nielsen TV ratings have been produced since the 1950-51 season; the Audimeter was used from 1950 and recorded the channels viewed, with paper diaries as another method.",
          [wk("Nielsen_ratings")]),
        F("tv_rating_versus_share", "A Nielsen rating of 20 means 20 percent of all US TV households tuned in to a program; a 30 share means 30 percent of the people watching TV at that time watched it.",
          ["source.brit_ac_nielsen"], [c(76, 4)],
          "Wikipedia (Nielsen ratings): a rating point is a percentage of all TV households, while a share is a percentage of those actually watching at the time.",
          [wk("Nielsen_ratings")]),
        F("tv_ratings_set_ad_rates", "Commercial networks use ratings, in part, to set advertising rates for each program and to decide which programs to continue or cancel.",
          ["source.brit_nielsen_ratings"], [c(76, 1), c(76, 4), c(80, 4)],
          "Wikipedia (Nielsen ratings): ratings determine advertising rates for schedules and programs and influence which shows are renewed or canceled.",
          [wk("Nielsen_ratings")]),
    ]),
    # ── Level 77 ──
    C("tv_public_broadcasting_act", "The Public Broadcasting Act of 1967",
      "Calls for less commercial TV led to the 1967 Act, proposed by the Carnegie Commission, which created the Corporation for Public Broadcasting and led to PBS and NPR.", 0.35, [
        F("tv_calls_for_bbc_style_tv", "After the quiz show hearings, columnists such as Walter Lippmann called for a new kind of television modeled on the BBC, calls that led toward a publicly funded system.",
          ["source.pbs_amex_quiz_aftermath"], [c(77, 2)],
          "Encyclopedia.com ('Quiz Show Scandals') and Television Heaven's history of the scandals note the calls for less commercial, BBC-style television that followed.",
          ["https://www.encyclopedia.com/media/encyclopedias-almanacs-transcripts-and-maps/quiz-show-scandals", "https://televisionheaven.co.uk/tv-history/the-quiz-show-scandals-of-the-1950s"]),
        F("tv_pba_signed_1967", "On November 7, 1967, President Lyndon Johnson signed the Public Broadcasting Act, which created the Corporation for Public Broadcasting.",
          ["source.presidency_lbj_pba_1967"], [c(77, 2), c(80, 3)],
          "Wikipedia (Public Broadcasting Act of 1967): effective November 7, 1967, the law established the Corporation for Public Broadcasting.",
          [wk("Public_Broadcasting_Act_of_1967")]),
        F("tv_pba_carnegie_commission", "The Public Broadcasting Act was proposed by the Carnegie Commission on educational television.",
          ["source.presidency_lbj_pba_1967"], [c(77, 2)],
          "Wikipedia (Public Broadcasting Act of 1967): public interest in educational TV came from the proposals of the Carnegie Commission on Educational Television.",
          [wk("Public_Broadcasting_Act_of_1967")]),
        F("tv_cpb_guarded_independent", "Johnson said the Corporation for Public Broadcasting would get part of its support from the government but be carefully guarded from government or party control.",
          ["source.presidency_lbj_pba_1967"], [c(77, 2)],
          "Wikipedia (Corporation for Public Broadcasting; Public Broadcasting Act of 1967): the CPB was set up as a private nonprofit corporation funded partly by Congress, insulated from direct government control.",
          [wk("Public_Broadcasting_Act_of_1967"), wk("Corporation_for_Public_Broadcasting")]),
        F("tv_pba_led_to_pbs_npr", "The Public Broadcasting Act led to the establishment of the Corporation for Public Broadcasting, PBS and NPR.",
          ["source.aapb_public_broadcasting_act"], [c(77, 2)],
          "Wikipedia (Public Broadcasting Act of 1967): the CPB it created went on to establish PBS (1969) and NPR (1970).",
          [wk("Public_Broadcasting_Act_of_1967")]),
    ]),
    C("tv_sesame_street", "Sesame Street teaches with TV's own tricks",
      "The Children's Television Workshop built Sesame Street (1969) with educators and researchers to prepare low-income children for school, borrowing commercial TV's pace and repetition.", 0.35, [
        F("tv_sesame_first_episode_letters", "The first episode of Sesame Street, sponsored by the letters W, S and E and the numbers 2 and 3, aired in the fall of 1969.",
          ["source.pbsnewshour_sesame_50"], [c(77, 1)],
          "Time ('Sesame Street First Episode Anniversary') and other anniversary coverage describe the November 10, 1969 first episode and its segments 'sponsored' by letters and numbers.",
          ["https://time.com/3563830/sesame-street-trivia/", wk("Sesame_Street")]),
        F("tv_ctw_founded_1968", "Joan Ganz Cooney, a New York public TV producer, founded the Children's Television Workshop in 1968 with backing from the Carnegie and Ford Foundations and the US Commissioner of Education.",
          ["source.pbs_cooney_they_made_america"], [c(77, 3)],
          "Wikipedia (Sesame Workshop): Cooney and Lloyd Morrisett, a Carnegie Corporation vice-president, spent 1966 to 1968 developing and funding the Workshop.",
          [wk("Sesame_Workshop"), wk("Joan_Ganz_Cooney")]),
        F("tv_sesame_goal_school_ready", "Sesame Street was designed by education professionals and child psychologists to help low-income and minority children aged 2 to 5 arrive at school better prepared.",
          ["source.pbsnewshour_sesame_50"], [c(77, 3), c(80, 4)],
          "Wikipedia (Sesame Street): one of the creators' primary goals was preparing young children for school, especially children from low-income families.",
          [wk("Sesame_Street")]),
        F("tv_sesame_research_planning", "Cooney consulted dozens of educators and set up a collaboration with educators and child development researchers to plan the show.",
          ["source.pbs_cooney_they_made_america"], [c(77, 3)],
          "Wikipedia (Sesame Street): the show's content was planned with a curriculum and formative research by educators and researchers.",
          [wk("Sesame_Street")]),
        F("tv_sesame_net_1969", "Sesame Street debuted in 1969 on National Educational Television, which became PBS in 1970, and features animations, live actors and Jim Henson's Muppets.",
          ["source.brit_sesame_street"], [c(77, 4)],
          "Wikipedia (Sesame Street): premiered on November 10, 1969, on NET and moved to its successor PBS; it combines Muppets, animation and live action.",
          [wk("Sesame_Street")]),
        F("tv_sesame_commercial_style", "Cooney based Sesame Street's fast pace, repeated segments and mix of formats on 1960s commercial television.",
          ["source.pbs_cooney_they_made_america"], [c(77, 4)],
          "Time ('Sesame Street First Episode Anniversary'): because kids love commercials, each episode contained short spots 'advertising' letters, numbers and ideas; Wikipedia notes its use of repetition.",
          ["https://time.com/3563830/sesame-street-trivia/", wk("Sesame_Street")]),
        F("tv_lbj_educates_exciting", "Signing the Public Broadcasting Act, Johnson said the new corporation would try to prove that what educates can also be exciting.",
          ["source.presidency_lbj_pba_1967"], [c(77, 4)],
          "American Archive of Public Broadcasting's exhibit on the Act quotes Johnson's signing remarks; the full text appears in the 1967 Public Papers of the Presidents.",
          ["https://americanarchive.org/exhibits/station-histories/public-broadcasting-act", wk("Public_Broadcasting_Act_of_1967")]),
    ]),
    # ── Level 78 ──
    C("tv_cable_origins_hbo", "Cable's start, HBO and CNN",
      "Cable began in the late 1940s to fix poor reception; HBO (1972) sold commercial-free films and went national by satellite in 1975; CNN (1980) brought 24-hour news.", 0.35, [
        F("tv_cable_reception_1940s", "US cable-television systems began in the late 1940s to improve reception of network broadcasts in remote and hilly areas.",
          ["source.brit_cable_television"], [c(78, 1)],
          "Wikipedia (Cable television in the United States): cable first became available in 1948, for example in Mahanoy City, Pennsylvania, where mountains blocked reception.",
          [wk("Cable_television_in_the_United_States")]),
        F("tv_cable_50_channels", "Some cable systems can deliver 50 or more channels.",
          ["source.brit_cable_television"], [c(78, 1)],
          "Wikipedia (Cable television in the United States): cable systems carry dozens to hundreds of channels, far more than over-the-air broadcasting.",
          [wk("Cable_television_in_the_United_States")]),
        F("tv_hbo_1972_commercial_free", "HBO started in 1972 showing uncut, commercial-free movies, and cable subscribers paid extra for it.",
          ["source.brit_hbo"], [c(78, 2)],
          "Wikipedia (HBO): launched November 8, 1972, as a pay service showing films without commercial interruption or editing.",
          [wk("HBO")]),
        F("tv_hbo_satellite_1975", "In 1975 HBO became the first American network to deliver its programming by satellite, and thus the first national cable channel.",
          ["source.brit_hbo"], [c(78, 2), c(80, 3)],
          "Wikipedia (HBO): it became the first television channel to begin transmitting via satellite, expanding a regional pay service nationally; 1975 in television records the September 30, 1975 satellite broadcast.",
          [wk("HBO"), wk("1975_in_American_television")]),
        F("tv_cnn_1980_24_hour", "CNN began in 1980 and ushered in the era of 24-hour television news.",
          ["source.brit_tv_us_cnn"], [c(78, 2)],
          "Wikipedia (CNN): launched June 1, 1980, by Ted Turner and Reese Schonfeld as the first 24-hour cable news channel.",
          [wk("CNN")]),
    ]),
    C("tv_audience_fragmentation", "Cable splits the audience",
      "As cable reached most homes, the three networks' share fell, and channels aimed at special interests divided viewers, ending the shared network era.", 0.4, [
        F("tv_cable_8_23_60_percent", "Only 8 percent of US households had basic cable in 1970, 23 percent in 1980, and nearly 60 percent by the end of the 1980s.",
          ["source.brit_tv_us_miniseries"], [c(78, 3)],
          "Lumen Learning's Media and Culture (9.3) gives the same 8 and 23 percent figures; Wikipedia (Cable television in the United States) counts 53 million cable households in 1989.",
          ["https://courses.lumenlearning.com/suny-massmedia/chapter/9-3-issues-and-trends-in-the-television-industry/", wk("Cable_television_in_the_United_States")]),
        F("tv_big_three_67_percent_1989", "By 1989 the three networks' share of the prime-time audience was down to 67 percent.",
          ["source.brit_tv_us_miniseries"], [c(78, 3)],
          "Lumen Learning's Media and Culture (9.3) and Encyclopedia.com ('Prime Time Audiences Gain More Choices') both give 67 percent in 1989.",
          ["https://courses.lumenlearning.com/suny-massmedia/chapter/9-3-issues-and-trends-in-the-television-industry/", "https://www.encyclopedia.com/arts/news-wires-white-papers-and-books/prime-time-audiences-gain-more-choices-1980s-2000s"]),
        F("tv_cable_niche_channels_1990s", "In the 1990s cable services aimed at specific audiences with specialized interests grew fastest, dividing the audience into smaller and smaller segments.",
          ["source.brit_tv_us_1990s"], [c(78, 4), c(80, 4)],
          "Encyclopedia.com ('Prime Time Audiences Gain More Choices, 1980s-2000s') describes cable's specialized channels splitting the once-mass network audience.",
          ["https://www.encyclopedia.com/arts/news-wires-white-papers-and-books/prime-time-audiences-gain-more-choices-1980s-2000s", wk("Network_era")]),
        F("tv_shared_era_ended_1990s", "Britannica says the era of a unified mass culture shaped by three networks ended, in effect, in the 1990s, when audiences stopped watching the same things at the same time.",
          ["source.brit_tv_us_1990s"], [c(78, 4)],
          "Wikipedia (Network era): the network era of three dominant networks and uniform programming gave way as cable and new networks spread in the 1980s and 1990s.",
          [wk("Network_era"), wk("Big_Three_television_networks")]),
    ]),
    # ── Level 79 ──
    C("tv_streaming_on_demand", "Streaming puts viewers in charge",
      "Netflix went from DVDs by mail (1997) to streaming (2007) to whole seasons at once (2013), letting viewers watch at their own pace on any screen.", 0.35, [
        F("tv_netflix_1997_dvd", "Netflix was founded in 1997 by Reed Hastings and Marc Randolph as a DVD-rental service; subscribers ordered online and received discs by mail.",
          ["source.brit_netflix"], [c(79, 2)],
          "Wikipedia (Netflix): Netflix, Inc. began a DVD-by-mail movie rental service nearly a decade before its 2007 streaming launch.",
          [wk("Netflix"), wk("Netflix,_Inc.")]),
        F("tv_netflix_streaming_2007", "In 2007 Netflix introduced streaming, letting subscribers watch directly over the Internet.",
          ["source.brit_netflix"], [c(79, 2)],
          "Wikipedia (Netflix): launched as a streaming service on January 16, 2007.",
          [wk("Netflix")]),
        F("tv_house_of_cards_all_at_once", "In February 2013 Netflix made all 13 first-season episodes of House of Cards available at once, instead of one episode a week.",
          ["source.tva_binge_bang_theory"], [c(79, 1), c(80, 3)],
          "Wikipedia (House of Cards (American TV series)): the first 13-episode season was released on February 1, 2013, one of the first series released all at once.",
          [wk("House_of_Cards_(American_TV_series)")]),
        F("tv_own_pace_any_screen", "Viewers quickly embraced having all episodes of a new season to watch at their own pace, on whatever screen they wish.",
          ["source.tva_everything_streamed"], [c(79, 2), c(80, 4)],
          "Wikipedia (Binge-watching): streaming services made whole seasons available on demand across devices, fueling binge viewing.",
          [wk("Binge-watching")]),
    ]),
    C("tv_binge_writing", "Binge viewing changes how series are written",
      "Binge-watching (many episodes in a row) is older than streaming, but autoplay made it effortless, and writers began shaping seasons as one long story.", 0.4, [
        F("tv_binge_watch_definition", "To binge-watch is to watch many or all episodes of a TV series in rapid succession.",
          ["source.mw_binge_watch"], [c(79, 3)],
          "Wikipedia (Binge-watching): the practice of watching entertainment content, usually a single TV show, for a prolonged time span.",
          [wk("Binge-watching")]),
        F("tv_binge_before_streaming", "Binge viewing predates Netflix: cable networks aired marathons of classic shows in the late 1990s, and binging became routine with TV on DVD a decade later.",
          ["source.tva_binge_bang_theory"], [c(79, 3)],
          "Wikipedia (Binge-watching; Marathon (media)): marathon viewing of TV series on cable and on DVD box sets preceded streaming.",
          [wk("Binge-watching"), wk("Marathon_(media)")]),
        F("tv_next_episode_autoplay", "On Netflix, the next episode of a series queues up automatically as soon as the previous one ends.",
          ["source.tva_binge_bang_theory"], [c(79, 3)],
          "Wikipedia (Binge-watching): streaming features such as autoplay of the next episode encourage binge viewing.",
          [wk("Binge-watching")]),
        F("tv_act_break_peril", "Broadcast TV writers build peril at the end of each act to keep viewers watching through commercial breaks.",
          ["source.thr_bernardin_binge_writing"], [c(79, 4)],
          "Scripps News ('Streaming and binge-watching have changed the way TV shows are written') and Fortune (2016) on network episodes built around commercial act breaks versus streaming structure.",
          ["https://www.scrippsnews.com/entertainment/streaming-has-changed-the-way-tv-shows-are-written", "https://fortune.com/2016/03/11/netflix-changing-game-network-tv"]),
        F("tv_ten_hour_movie", "Writer Marc Bernardin notes that binge viewers skip the 'previously on' recap and that writers describe a streaming season as 'breaking a 10-hour movie'.",
          ["source.thr_bernardin_binge_writing"], [c(79, 4)],
          "Scripps News ('Streaming and binge-watching have changed the way TV shows are written'): streaming series are written as one continuous story, with less need for recaps and cliffhangers.",
          ["https://www.scrippsnews.com/entertainment/streaming-has-changed-the-way-tv-shows-are-written"]),
    ]),
    # ── Level 80 ──
    C("tv_vast_wasteland", "Newton Minow's 'vast wasteland'",
      "In 1961 FCC chairman Newton Minow called commercial TV a vast wasteland, pushed the networks toward longer news and won the first federal money for educational TV.", 0.35, [
        F("tv_minow_wasteland_1961", "In May 1961, FCC chairman Newton Minow, appointed by President Kennedy, told the National Association of Broadcasters that commercial television was a 'vast wasteland' and argued for public service television.",
          ["source.aapb_minow_collection"], [c(80, 1)],
          "Wikipedia (Television and the Public Interest): Minow's May 9, 1961 speech to the National Association of Broadcasters called commercial programming a 'vast wasteland'; he had been appointed by John F. Kennedy.",
          [wk("Television_and_the_Public_Interest"), wk("Newton_N._Minow")]),
        F("tv_minow_news_expansion", "Minow encouraged the commercial networks to expand their nightly news from 15 minutes to half an hour.",
          ["source.aapb_minow_collection"], [c(80, 2)],
          "Wikipedia (Newton N. Minow): as FCC chairman he pressed broadcasters on public affairs programming; the network newscasts expanded to 30 minutes in 1963.",
          [wk("Newton_N._Minow"), wk("CBS_Evening_News")]),
        F("tv_minow_etv_act_1962", "Minow pushed through the Educational Television Facilities Act of 1962, the first federal funds for educational TV, a step that led five years later to the Public Broadcasting Act of 1967.",
          ["source.aapb_minow_collection"], [c(80, 2)],
          "Wikipedia (Newton N. Minow; Public Broadcasting Act of 1967): Minow supported the 1962 Educational Television Facilities Act, which provided federal grants for educational stations before the 1967 Act.",
          [wk("Newton_N._Minow"), wk("Public_Broadcasting_Act_of_1967")]),
    ]),
]
