ACC = "2026-09-27"
B = "Encyclopaedia Britannica"

def src(id, title, url, publisher, notes):
    return {"id": id, "title": title, "url": url, "publisher": publisher,
            "license": "reference_only", "accessedAt": ACC, "verified": False, "notes": notes}

SOURCES = [
    src("source.brit_tv_us_overview", "Television in the United States", "https://www.britannica.com/art/television-in-the-United-States", B,
        "Cited for: TV first regarded as radio with pictures; in 1948 radio still the number one broadcast medium; four networks (ABC, CBS, NBC, DuMont) and DuMont folding; radio stars reluctant; Berle and Texaco Star Theatre as TV's first hit; under 2 percent of homes with sets at its debut, 70 percent by 1956."),
    src("source.brit_cbs", "CBS Corporation", "https://www.britannica.com/money/CBS-Corporation", B,
        "Cited for: CBS began as a radio network in the late 1920s under William S. Paley; the 1948 talent raid on NBC (Jack Benny, Burns and Allen, Amos 'n' Andy's creators) and the stars' success on TV."),
    src("source.brit_broadcasting", "Broadcasting", "https://www.britannica.com/technology/broadcasting", B,
        "Cited for: advertising became the principal means of support for US broadcasting; sponsored network programs furnished revenue to the network and its stations."),
    src("source.brit_texaco_star_theatre", "The Texaco Star Theatre", "https://www.britannica.com/topic/The-Texaco-Star-Theatre", B,
        "Cited for: premiered 1948; Milton Berle as Mr. Television; its live variety show led to a dramatic increase in TV set purchases."),
    src("source.brit_tv_us_kennedy_nixon", "Television in the United States: The Kennedy-Nixon debates", "https://www.britannica.com/art/television-in-the-United-States/The-Kennedy-Nixon-debates", B,
        "Cited for: the first televised presidential debate on September 26, 1960, simulcast on all three networks, about 70 million viewers; nearly 90 percent of homes had TV by 1960."),
    src("source.brit_tv_us_miniseries", "Television in the United States: The era of the miniseries", "https://www.britannica.com/art/television-in-the-United-States/The-era-of-the-miniseries", B,
        "Cited for: more than 90 percent of the prime-time audience on ABC, CBS or NBC in the late 1970s, 67 percent by 1989; basic cable in 8 percent of homes in 1970, 23 percent in 1980, nearly 60 percent by the end of the 1980s."),
    src("source.brit_tv_us_1990s", "Television in the United States: The 1990s, the loss of shared experience", "https://www.britannica.com/art/television-in-the-United-States/The-1990s-the-loss-of-shared-experience", B,
        "Cited for: broadcasting as cultural glue from 1929 to 1989; three-company control of TV produced a unified mass culture that ended in effect in the 1990s; cable services aimed at specific audiences divided viewers."),
    src("source.brit_tv_us_early_genres", "Television in the United States: Early genres", "https://www.britannica.com/art/television-in-the-United-States/Early-genres", B,
        "Cited for: anthology dramas (Kraft Television Theatre, Studio One); writers Paddy Chayefsky, Rod Serling, Gore Vidal; Marty (1955) based on a 1953 TV episode and winning best picture."),
    src("source.brit_tv_us_late_golden_age", "Television in the United States: The late Golden Age", "https://www.britannica.com/art/television-in-the-United-States/The-late-Golden-Age", B,
        "Cited for: most network TV live in 1953 and a minority by 1960; production moving to Los Angeles; filmed shows could earn income indefinitely from reruns."),
    src("source.brit_tv_us_sitcoms", "Television in the United States: Sitcoms", "https://www.britannica.com/art/television-in-the-United-States/Sitcoms", B,
        "Cited for: the sitcom as a 30-minute format with a continuing cast in the same setting; I Love Lucy (CBS, 1951-57) debuted October 1951, shot on film in Hollywood as an episodic series."),
    src("source.brit_tv_us_cnn", "Television in the United States: CNN", "https://www.britannica.com/art/television-in-the-United-States/CNN", B,
        "Cited for: CNN began in 1980 and ushered in the era of 24-hour news."),
    src("source.ethw_ampex_vtr_1956", "Milestones: Ampex Videotape Recorder, 1956", "https://ethw.org/Milestones:Ampex_Videotape_Recorder,_1956", "Engineering and Technology History Wiki (IEEE History Center)",
        "Cited for: before 1956 TV could be recorded only on film, by pointing a movie camera at a monitor (kinescope); poor quality and expense; by 1954 broadcasters used more raw film than the movie industry; Ampex's 1956 videotape recorder replaced kinescopes."),
    src("source.tva_videotape_debut", "50 Years Ago: Videotape Debuts", "https://interviews.televisionacademy.com/news/50-years-ago-videotape-debuts", "Television Academy Foundation (The Interviews)",
        "Cited for: on November 30, 1956, CBS used an Ampex recorder in Hollywood to tape a live New York newscast and rebroadcast it later to the West Coast; kinescopes as filmed TV screens."),
    src("source.loc_lucy_cast_crew_set", "I Love Lucy: An American Legend: The Cast, Crew, and Set", "https://www.loc.gov/exhibits/i-love-lucy/the-cast-crew-and-set.html", "Library of Congress",
        "Cited for: I Love Lucy adapted from My Favorite Husband; Karl Freund and Marc Daniels generally credited with the three-camera technique before a live audience that became the sitcom standard; the apartment-building setting."),
    src("source.loc_lcib_we_still_love_lucy", "We Still Love Lucy (Library of Congress Information Bulletin, September/October 2011)", "https://www.loc.gov/loc/lcib/110910/lucy.html", "Library of Congress",
        "Cited for: most TV then made in the East and shown to western time zones as kinescopes ('like watching TV through a cheesecloth'); Ball, Arnaz and Oppenheimer chose to produce in Hollywood on 35 mm film before a live audience; My Favorite Husband on CBS radio from 1948; reruns from 1955."),
    src("source.deadline_dann_cahn", "Dann Cahn Dead: 'I Love Lucy' Editor, Multicamera Pioneer", "https://deadline.com/2012/11/dann-cahn-dead-editor-of-i-love-lucy-multicamera-tv-pioneer-376730/", "Deadline",
        "Cited for: I Love Lucy used three motion picture cameras and was filmed continuously in sequence like a stage play; editor Dann Cahn cut it on a Moviola with three picture heads and one sound head."),
    src("source.brit_walter_cronkite", "Walter Cronkite", "https://www.britannica.com/biography/Walter-Cronkite", B,
        "Cited for: anchor of the CBS evening news from 1962, when it grew from 15 to 30 minutes, the first half-hour nightly network newscast; 1968 trip to Vietnam after the Tet Offensive and conclusion that the war could end only in stalemate."),
    src("source.daedalus_mandelbaum_tv_war", "Vietnam: The Television War (Michael Mandelbaum, Daedalus, Fall 1982)", "https://www.amacad.org/publication/daedalus/vietnam-tv-war", "American Academy of Arts and Sciences",
        "Cited for: in 1963 the evening national newscasts expanded from 15 minutes to half an hour; Vietnam the first televised war; film of airplanes and troops on patrol; cans of film shipped by air."),
    src("source.tva_quiz_show_scandals", "Quiz Show Scandals", "https://interviews.televisionacademy.com/topics/quiz-show-scandals", "Television Academy Foundation (The Interviews)",
        "Cited for: accusations in 1958 that quiz shows were rigged and contestants coached; 1959 House hearings; networks leery of single sponsorship afterward, selling time in 15-, 30- and 60-second units."),
    src("source.pbs_amex_quiz_aftermath", "The Aftermath of the Quiz Show Scandal (American Experience)", "https://www.pbs.org/wgbh/americanexperience/features/quizshow-aftermath-quiz-show-scandal/", "PBS / WGBH",
        "Cited for: producers took control of shows and stations sold commercial time on the magazine model; removing advertisers from shows ended their urge to interfere; 1960 Communications Act amendments; Walter Lippmann's call for BBC-style TV."),
    src("source.brit_ac_nielsen", "A.C. Nielsen Co.", "https://www.britannica.com/money/A-C-Nielsen", B,
        "Cited for: TV ratings from 1950 based on a sample of more than 1,000 TV homes with Audimeters, plus diaries; definitions of a rating and a share."),
    src("source.brit_nielsen_ratings", "Nielsen ratings", "https://www.britannica.com/art/Nielsen-ratings", B,
        "Cited for: networks use ratings in part to set advertising rates for each program and to decide which programs to keep or cancel."),
    src("source.presidency_lbj_pba_1967", "Remarks Upon Signing the Public Broadcasting Act of 1967 (Lyndon B. Johnson, November 7, 1967)", "https://www.presidency.ucsb.edu/documents/remarks-upon-signing-the-public-broadcasting-act-1967", "The American Presidency Project, UC Santa Barbara",
        "Cited for: signing on November 7, 1967; the Act builds the Corporation for Public Broadcasting, partly government-funded but guarded from government or party control; the Carnegie Commission proposed it; 'what educates can also be exciting'."),
    src("source.aapb_public_broadcasting_act", "Public Broadcasting Act of 1967", "https://americanarchive.org/exhibits/station-histories/public-broadcasting-act", "American Archive of Public Broadcasting (Library of Congress and GBH)",
        "Cited for: the Act led to the Corporation for Public Broadcasting, PBS and NPR."),
    src("source.pbs_cooney_they_made_america", "Who Made America? Innovators: Joan Ganz Cooney", "https://www.pbs.org/wgbh/theymadeamerica/whomade/cooney_hi.html", "PBS",
        "Cited for: Cooney founded the Children's Television Workshop in 1968 with Carnegie, Ford and US Commissioner of Education backing; worked with educators and researchers; based the show's fast pace and repeated segments on commercial TV."),
    src("source.pbsnewshour_sesame_50", "'Sesame Street' turns 50", "https://www.pbs.org/newshour/arts/sesame-street-turns-50", "PBS NewsHour",
        "Cited for: the first episode, sponsored by the letters W, S and E and the numbers 2 and 3, aired in fall 1969; designed by educators and child psychologists to help low-income and minority children aged 2 to 5 prepare for school."),
    src("source.brit_sesame_street", "Sesame Street", "https://www.britannica.com/topic/Sesame-Street", B,
        "Cited for: debuted in 1969 on National Educational Television, which became PBS in 1970; animations, live actors and Jim Henson's Muppets."),
    src("source.brit_cable_television", "Cable television", "https://www.britannica.com/technology/cable-television", B,
        "Cited for: US cable systems began in the late 1940s to improve reception in remote and hilly areas; some systems deliver 50 or more channels."),
    src("source.brit_hbo", "HBO", "https://www.britannica.com/money/HBO", B,
        "Cited for: started in 1972 with uncut, commercial-free movies for which subscribers paid extra; in 1975 the first American network to deliver programming by satellite, so the first national cable channel."),
    src("source.brit_netflix", "Netflix, Inc.", "https://www.britannica.com/money/Netflix-Inc", B,
        "Cited for: founded 1997 by Reed Hastings and Marc Randolph as a DVD-rental service ordered online and delivered by mail; streaming introduced in 2007."),
    src("source.tva_binge_bang_theory", "The Binge Bang Theory (Daniel Frankel)", "https://www.televisionacademy.com/features/news/features/binge-bang-theory", "Television Academy",
        "Cited for: in February 2013 Netflix released all 13 first-season episodes of House of Cards at once; binge viewing predates Netflix (1990s cable marathons, TV on DVD); the next episode queues automatically."),
    src("source.tva_everything_streamed", "Everything Streamed Is New Again", "https://www.televisionacademy.com/features/news/industry-news/everything-streamed-new-again", "Television Academy",
        "Cited for: viewers embraced having a whole season to watch at their own pace, on whatever screen they wish."),
    src("source.mw_binge_watch", "Binge-watch (definition)", "https://www.merriam-webster.com/dictionary/binge-watch", "Merriam-Webster",
        "Cited for: to binge-watch is to watch many or all episodes of a TV series in rapid succession."),
    src("source.thr_bernardin_binge_writing", "How Binge-Watching Has Changed TV Writing (Marc Bernardin, guest column)", "https://www.hollywoodreporter.com/tv/tv-news/has-binge-watching-changed-tv-writing-1118988/", "The Hollywood Reporter",
        "Cited for: broadcast writers build peril at the end of each act to hold viewers through commercial breaks; binge viewers skip the 'previously on'; writers speak of 'breaking a 10-hour movie'."),
    src("source.aapb_minow_collection", "Broadcasting in the Public Interest: The Newton Minow Collection", "https://americanarchive.org/special_collections/newtonminow", "American Archive of Public Broadcasting (Library of Congress and GBH)",
        "Cited for: FCC chairman Newton Minow, appointed by Kennedy in 1961, called commercial TV a 'vast wasteland' in a May 1961 speech to the National Association of Broadcasters; urged the networks to expand nightly news to half an hour; won the Educational Television Facilities Act of 1962, which led toward the Public Broadcasting Act of 1967."),
]
