/**
 * Level art registry. React Native needs a literal require() for every image,
 * so this writes app/src/content/art.ts from whatever files are in
 * app/assets/images/art/ (named by image ID, e.g. astronomy.mars.png).
 *
 *   npm run art:sync             # write the registry
 *   npm run art:sync -- --check  # fail if it's out of date (part of npm run check)
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ArtId } from '@brainscroll/core';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'app', 'assets', 'images', 'art');
const out = join(root, 'app', 'src', 'content', 'art.ts');

const files = readdirSync(dir).filter((f) => /\.(png|webp)$/.test(f)).sort();
const entries: string[] = [];
const seen = new Set<string>();
for (const f of files) {
  const id = f.replace(/\.(png|webp)$/, '');
  if (!ArtId.safeParse(id).success) {
    console.error(`✖ ${f}: name it by its image ID, like astronomy.mars.png`);
    process.exit(1);
  }
  if (seen.has(id)) {
    console.error(`✖ ${id}: both a .png and a .webp; keep one`);
    process.exit(1);
  }
  seen.add(id);
  entries.push(`  '${id}': require('../../assets/images/art/${f}'),`);
}

const ts = `// Generated by \`npm run art:sync\` from app/assets/images/art/. Don't edit by hand.
import type { ImageSourcePropType } from 'react-native';

export const ART: Record<string, ImageSourcePropType> = {
${entries.join('\n')}${entries.length ? '\n' : ''}};
`;

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(out, 'utf8');
  } catch {}
  if (current !== ts) {
    console.error('app/src/content/art.ts is out of date; run npm run art:sync');
    process.exit(1);
  }
  console.log(`art registry is up to date (${entries.length} images)`);
} else {
  writeFileSync(out, ts);
  console.log(`wrote ${entries.length} images → app/src/content/art.ts`);
}
