/**
 * Level art registry. Drop finished images in app/assets/images/art/ (named by
 * image ID, e.g. astronomy.mars.png); this packs them four to a sheet in
 * app/assets/images/art-sheets/ (lib/art-sheets.ts says why and how) and writes
 * app/src/content/art.ts, the map from image ID to its sheet and cell. React
 * Native needs a literal require() for every file, hence the generated file.
 *
 *   npm run art:sync             # pack new or changed images, write the registry
 *   npm run art:sync -- --check  # fail if either is out of date (part of npm run check)
 */
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import { ArtId } from '@brainscroll/core';
import { planSheets, SHEET, type SheetLayout } from './lib/art-sheets';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'app', 'assets', 'images', 'art');
const sheetDir = join(root, 'app', 'assets', 'images', 'art-sheets');
const layoutFile = join(sheetDir, 'layout.json');
const out = join(root, 'app', 'src', 'content', 'art.ts');
const check = process.argv.includes('--check');

const files = readdirSync(dir).filter((f) => /\.(png|webp)$/.test(f)).sort();
const fileOf = new Map<string, string>();
for (const f of files) {
  const id = f.replace(/\.(png|webp)$/, '');
  if (!ArtId.safeParse(id).success) {
    console.error(`✖ ${f}: name it by its image ID, like astronomy.mars.png`);
    process.exit(1);
  }
  if (fileOf.has(id)) {
    console.error(`✖ ${id}: both a .png and a .webp; keep one`);
    process.exit(1);
  }
  fileOf.set(id, join(dir, f));
}

// New images are packed by first use (skill by skill, level by level), so a map's pictures share sheets.
const firstUse: string[] = [];
const skillsDir = join(root, 'content', 'skills');
for (const skill of readdirSync(skillsDir).sort()) {
  const levels = join(skillsDir, skill, 'levels');
  if (!existsSync(levels)) continue;
  for (const f of readdirSync(levels).filter((f) => f.endsWith('.json')).sort()) {
    const art = (JSON.parse(readFileSync(join(levels, f), 'utf8')) as { art?: string }).art;
    if (art) firstUse.push(art);
  }
}
firstUse.push(...Object.values(JSON.parse(readFileSync(join(root, 'content', 'card-art.json'), 'utf8')) as Record<string, string>));

const fileHash = (id: string) => createHash('sha256').update(readFileSync(fileOf.get(id)!)).digest('hex');
const previous = existsSync(layoutFile) ? (JSON.parse(readFileSync(layoutFile, 'utf8')) as SheetLayout) : null;
const layout = planSheets(previous, [...fileOf.keys()], firstUse, fileHash);
const sheetFile = (hash: string) => `${hash}.webp`;

const place = [...layout.sheets.entries()].flatMap(([s, sheet]) => sheet.ids.flatMap((id, cell) => (id ? [[id, s, cell] as const] : [])));
place.sort(([a], [b]) => a.localeCompare(b));
const ts = `// Generated by \`npm run art:sync\` from app/assets/images/art/. Don't edit by hand.
import type { ImageSourcePropType } from 'react-native';

/** Level art, four images to a sheet (scripts/lib/art-sheets.ts): cells of ${SHEET.CELL} px, ${SHEET.COLS} across, each with a ${SHEET.EDGE} px edge. */
export const ART_SHEET = { cols: ${SHEET.COLS}, rows: ${SHEET.ROWS}, cell: ${SHEET.CELL}, edge: ${SHEET.EDGE} } as const;

export const ART_SHEETS: ImageSourcePropType[] = [
${layout.sheets.map((s) => `  require('../../assets/images/art-sheets/${sheetFile(s.hash)}'),`).join('\n')}${layout.sheets.length ? '\n' : ''}];

/** Each image's sheet and cell (left to right, top to bottom). */
export const ART: Record<string, readonly [sheet: number, cell: number]> = {
${place.map(([id, s, cell]) => `  '${id}': [${s}, ${cell}],`).join('\n')}${place.length ? '\n' : ''}};
`;
const layoutJson = `${JSON.stringify(layout, null, 2)}\n`;
const wanted = new Set(layout.sheets.map((s) => sheetFile(s.hash)));
const onDisk = existsSync(sheetDir) ? readdirSync(sheetDir).filter((f) => f.endsWith('.webp')) : [];

if (check) {
  const read = (p: string) => (existsSync(p) ? readFileSync(p, 'utf8') : '');
  const problems = [
    read(out) !== ts && 'app/src/content/art.ts is out of date',
    read(layoutFile) !== layoutJson && 'app/assets/images/art-sheets/layout.json is out of date',
    [...wanted].some((f) => !onDisk.includes(f)) && 'a sheet is missing',
    onDisk.some((f) => !wanted.has(f)) && 'a sheet no image uses is still there',
  ].filter(Boolean);
  if (problems.length) {
    console.error(`${problems.join('; ')}: run npm run art:sync`);
    process.exit(1);
  }
  console.log(`art registry is up to date (${place.length} images on ${layout.sheets.length} sheets)`);
  process.exit(0);
}

/** One sheet: each image scaled to a cell, its edge pixels copied outward, on a transparent ground. */
async function pack(ids: (string | null)[]) {
  const box = SHEET.CELL + 2 * SHEET.EDGE;
  const cells = await Promise.all(
    ids.map(async (id, i) => {
      if (!id) return null;
      const input = await sharp(fileOf.get(id)!)
        .resize(SHEET.CELL, SHEET.CELL, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
        .ensureAlpha()
        .extend({ top: SHEET.EDGE, bottom: SHEET.EDGE, left: SHEET.EDGE, right: SHEET.EDGE, extendWith: 'copy' })
        .raw()
        .toBuffer();
      return { input, raw: { width: box, height: box, channels: 4 as const }, left: (i % SHEET.COLS) * box, top: Math.floor(i / SHEET.COLS) * box };
    }),
  );
  return sharp({ create: { width: SHEET.COLS * box, height: SHEET.ROWS * box, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } })
    .composite(cells.filter((c) => c !== null))
    .webp({ quality: SHEET.QUALITY, alphaQuality: 100, effort: 6 })
    .toBuffer();
}

mkdirSync(sheetDir, { recursive: true });
let packed = 0;
for (const s of layout.sheets) {
  if (onDisk.includes(sheetFile(s.hash))) continue;
  writeFileSync(join(sheetDir, sheetFile(s.hash)), await pack(s.ids));
  packed++;
}
for (const f of onDisk) if (!wanted.has(f)) rmSync(join(sheetDir, f));
writeFileSync(layoutFile, layoutJson);
writeFileSync(out, ts);
console.log(`wrote ${place.length} images on ${layout.sheets.length} sheets (${packed} packed) → app/src/content/art.ts`);
