/**
 * Compiles content/ into the app's offline content (app/src/content/built/).
 * Refuses to build if validation has errors.
 *
 *   npm run content:build           # write it
 *   npm run content:build -- --check  # fail if the committed files are stale (CI)
 *
 * Split so the app starts fast: `index.json` is small and loaded at launch
 * (subjects, skills, chapters, concept titles and each level's title, number
 * and art). Each skill's full lessons are a separate `levels/<slug>.json`,
 * evaluated only when a lesson from that skill is first opened
 * (`levels/index.ts` holds one lazy require per skill).
 *
 * `learner-levels/` is the same lessons with the answer key removed (no
 * `correct` flags, rationales or explanations), like the server's
 * learner_bundle. Builds that talk to Supabase ship only that copy
 * (app/metro.config.js picks it), so the answers never reach a store build;
 * only the development harness, which grades on-device, ships the full one.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { validateContent, type Level } from '@brainscroll/core';
import { loadContent } from './lib/load-content';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'app', 'src', 'content', 'built');

const { issues, content } = validateContent(loadContent(join(root, 'content')));
const errors = issues.filter((i) => i.severity === 'error');
if (errors.length) {
  for (const e of errors) console.error(`✖ ${e.where}: ${e.message}`);
  console.error(`\nContent has ${errors.length} errors; run npm run validate:content`);
  process.exit(1);
}

/** A skill's file name and card-id segment: the last part of its id (`skill.science.astronomy` → `astronomy`). */
const skillSlug = (skillId: string) => skillId.split('.').at(-1)!;

// A skill with a syllabus but no levels yet is planned, not shipped: keep it out of the app.
const shipped = content.skills.filter((s) => content.levels.some((l) => l.skillId === s.id)).sort((a, b) => a.order - b.order);
const levels = [...content.levels].sort((a, b) => a.skillId.localeCompare(b.skillId) || a.number - b.number);

const index = {
  subjects: [...content.subjects].sort((a, b) => a.order - b.order),
  skills: shipped,
  concepts: [...content.concepts].sort((a, b) => a.id.localeCompare(b.id)).map(({ id, title }) => ({ id, title })),
  // What screens show without opening a lesson.
  levels: levels.map(({ id, skillId, number, type, revision, title, art }) => ({ id, skillId, number, type, revision, title, ...(art ? { art } : {}) })),
  // Chapter titles for the level path, from each shipped skill's syllabus, and
  // what each chapter taught: the recap card on its last level. That's the proof
  // on the checkpoint's Level Complete and the chapter's meaning on the skill map.
  chapters: Object.fromEntries(
    content.syllabi
      .filter((s) => shipped.some((k) => k.id === s.skillId))
      .map((s) => [
        s.skillId,
        s.chapters.map(({ number, title, levels: range }) => {
          const recap = levels.find((l) => l.skillId === s.skillId && l.number === range[1])?.cards.find((c) => c.type === 'checkpoint');
          return { number, title, levels: range, ...(recap?.type === 'checkpoint' ? { learned: recap.learned } : {}) };
        }),
      ]),
  ),
};

const files = new Map<string, string>();
const json = (v: unknown) => JSON.stringify(v) + '\n';
files.set('index.json', json(index));
for (const s of shipped) files.set(`levels/${skillSlug(s.id)}.json`, json(levels.filter((l: Level) => l.skillId === s.id)));
/** Mirrors SQL learner_bundle(): what a learner's device may know about a question. */
const stripAnswers = (l: Level): Level => ({
  ...l,
  questions: l.questions.map((q) => ({ ...q, explanation: '', options: q.options.map(({ rationale: _r, ...o }) => ({ ...o, correct: false })) })),
});
for (const s of shipped) files.set(`learner-levels/${skillSlug(s.id)}.json`, json(levels.filter((l: Level) => l.skillId === s.id).map(stripAnswers)));
const loaderIndex = (what: string) =>
  [
    '// Generated by `npm run content:build`. Do not edit.',
    "import type { Level } from '@brainscroll/core';",
    '',
    `/** Each skill's ${what}, evaluated on first use (a require inside a function runs only when called). */`,
    'export const SKILL_LEVELS: Record<string, () => Level[]> = {',
    ...shipped.map((s) => `  '${s.id}': () => require('./${skillSlug(s.id)}.json') as Level[],`),
    '};',
    '',
  ].join('\n');
files.set('learner-levels/index.ts', loaderIndex('lessons without the answer key'));
files.set('levels/index.ts', loaderIndex('full lessons, answers included (development harness only)'));

const existing = (dir: string): string[] =>
  existsSync(dir) ? readdirSync(dir, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? existing(join(dir, e.name)).map((f) => `${e.name}/${f}`) : [e.name])) : [];

if (process.argv.includes('--check')) {
  const stale = [...files].filter(([f, body]) => !existsSync(join(outDir, f)) || readFileSync(join(outDir, f), 'utf8') !== body).map(([f]) => f);
  const extra = existing(outDir).filter((f) => !files.has(f));
  if (stale.length || extra.length) {
    console.error(`app/src/content/built is out of date (${[...stale, ...extra].slice(0, 5).join(', ')}); run npm run content:build`);
    process.exit(1);
  }
  console.log('content bundle is up to date');
} else {
  rmSync(outDir, { recursive: true, force: true });
  for (const [f, body] of files) {
    mkdirSync(dirname(join(outDir, f)), { recursive: true });
    writeFileSync(join(outDir, f), body);
  }
  const legacy = join(root, 'app', 'src', 'content', 'bundle.json');
  if (existsSync(legacy)) rmSync(legacy);
  console.log(`wrote ${levels.length} levels in ${shipped.length} skills → app/src/content/built (index ${Math.round(files.get('index.json')!.length / 1024)} KB)`);
}
