/**
 * Claim verification tools. Humans verify; these scripts never set "verified"
 * on their own.
 *
 *   npm run verify:report                       # write docs/verification/<skill>.md + .csv
 *   npm run verify:sync                         # add missing (fact, source) records as "unverified"
 *   npm run verify:record -- <factId> <sourceId> --status verified --by "Name" --quote "text from the page" [--notes "…"]
 *   npm run verify:import-csv -- docs/verification/astronomy.csv --by "Name"
 *                                               # apply status/quote/notes filled in the CSV
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { VERIFICATION_STATUSES, validateContent, type VerificationRecord } from '@brainscroll/core';
import { claimIndex, skillSlugOf, type ClaimRow } from './lib/claims';
import { loadContent } from './lib/load-content';

const repo = join(dirname(fileURLToPath(import.meta.url)), '..');
const contentRoot = join(repo, 'content');
const ledgerPath = join(contentRoot, 'verification.json');
const outDir = join(repo, 'docs', 'verification');

const [command, ...args] = process.argv.slice(2);
const flag = (name: string) => {
  const i = args.indexOf(`--${name}`);
  return i >= 0 ? args[i + 1] : undefined;
};
const today = () => new Date().toISOString().slice(0, 10);

function load() {
  const { issues, content } = validateContent(loadContent(contentRoot));
  const errors = issues.filter((i) => i.severity === 'error' && !i.where.startsWith('verification.json'));
  if (errors.length) {
    for (const e of errors) console.error(`✖ ${e.where}: ${e.message}`);
    process.exit(1);
  }
  return content;
}

function readLedger(): VerificationRecord[] {
  return JSON.parse(readFileSync(ledgerPath, 'utf8')) as VerificationRecord[];
}
function writeLedger(rows: VerificationRecord[]) {
  rows.sort((a, b) => a.factId.localeCompare(b.factId) || a.sourceId.localeCompare(b.sourceId));
  writeFileSync(ledgerPath, JSON.stringify(rows, null, 2) + '\n');
}

function setRecord(ledger: VerificationRecord[], factId: string, sourceId: string, patch: Partial<VerificationRecord>): VerificationRecord {
  let rec = ledger.find((r) => r.factId === factId && r.sourceId === sourceId);
  if (!rec) throw new Error(`no record for ${factId} / ${sourceId} (run npm run verify:sync, and check the fact cites that source)`);
  Object.assign(rec, patch);
  if (rec.status === 'verified' && !(rec.checkedBy && rec.checkedAt && rec.supportingQuote))
    throw new Error(`${factId} / ${sourceId}: "verified" needs --by and --quote (the supporting text from the page)`);
  return rec;
}

const esc = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
const csvCell = (s: string | undefined) => `"${(s ?? '').replace(/"/g, '""')}"`;
const BOX: Record<VerificationRecord['status'], string> = { unverified: '☐', verified: '☑', incorrect: '✗', unsupported: '?' };

function report() {
  const content = load();
  const rows = claimIndex(content);
  mkdirSync(outDir, { recursive: true });
  const bySkill = new Map<string, ClaimRow[]>();
  for (const r of rows) bySkill.set(skillSlugOf(r.fact.id), [...(bySkill.get(skillSlugOf(r.fact.id)) ?? []), r]);

  for (const [skill, list] of bySkill) {
    const counts = Object.fromEntries(VERIFICATION_STATUSES.map((s) => [s, list.filter((r) => r.record.status === s).length]));
    const facts = new Set(list.map((r) => r.fact.id));
    const factsDone = [...facts].filter((f) => list.filter((r) => r.fact.id === f).every((r) => r.record.status === 'verified')).length;
    const md: string[] = [
      `# ${skill[0]!.toUpperCase()}${skill.slice(1)} claim verification checklist`,
      '',
      '> Generated by `npm run verify:report` from `content/`. Do not edit by hand; record results with the commands below and regenerate.',
      '',
      `**Progress:** ${factsDone} / ${facts.size} claims fully verified · ${counts.verified} verified, ${counts.unverified} unverified, ${counts.incorrect} incorrect, ${counts.unsupported} unsupported (${list.length} claim–source checks).`,
      '',
      '## How to verify',
      '',
      '1. Open the source URL. Each section below is one source page with every claim that cites it.',
      '2. For each claim, find the sentence on the page that supports it. Numbers must match (rounding like "about" is fine; a different figure is not).',
      '3. Record the result (or fill in the CSV and run `npm run verify:import-csv -- docs/verification/' + skill + '.csv --by "Your Name"`):',
      '   - **verified**: the page states it. Paste the supporting sentence as the quote.',
      '   - **unsupported**: the page does not say it. Find a better source or change the claim.',
      '   - **incorrect**: the page (or better evidence) contradicts it. The card/question must be revised in a new revision.',
      '4. A level can only be published when every claim it states or teaches is verified against every source it cites. `npm run validate:content` enforces this.',
      '',
      '"Pre-check" notes were written while drafting. They point at what to look at closely. They are not verification.',
      '',
    ];
    const bySource = new Map<string, ClaimRow[]>();
    for (const r of list) bySource.set(r.sourceId, [...(bySource.get(r.sourceId) ?? []), r]);
    for (const [sid, srows] of [...bySource].sort(([a], [b]) => a.localeCompare(b))) {
      const s = srows[0]!.source;
      md.push(`## ${s ? `${s.title} (${s.publisher})` : sid}`, '');
      md.push(`- **Source:** \`${sid}\``);
      if (s) md.push(`- **URL:** ${s.url}`, `- **License:** ${s.license} · **Accessed:** ${s.accessedAt} · **Source record checked (URL/licence):** ${s.verified ? 'yes' : 'no'}`);
      md.push('');
      for (const r of srows.sort((a, b) => a.fact.id.localeCompare(b.fact.id))) {
        md.push(`### ${BOX[r.record.status]} \`${r.fact.id}\`: ${r.record.status}`, '');
        md.push(`> **Claim:** ${r.fact.text}`, '');
        md.push(`- **Concept:** ${r.concept.title} (\`${r.concept.id}\`)`);
        if (r.appearsIn.length) {
          md.push('- **Appears in:**');
          for (const a of r.appearsIn) md.push(`  - L${a.level.number} “${a.level.title}” · \`${a.card.id}\` (${a.card.type}): ${esc(a.text)}`);
        } else md.push('- **Appears in:** (no card named; add `cardIds`)');
        if (r.testedBy.length) {
          md.push('- **Tested by:**');
          for (const t of r.testedBy) md.push(`  - L${t.level.number} \`${t.question.id}\`: ${esc(t.question.prompt)} → **${esc(t.answer)}**`);
        }
        if (r.record.preCheck) md.push(`- **Pre-check:** ${esc(r.record.preCheck)}`);
        if (r.record.status !== 'unverified')
          md.push(`- **Checked by:** ${r.record.checkedBy ?? 'not yet'} on ${r.record.checkedAt ?? 'n/a'}`, `- **Quote:** ${r.record.supportingQuote ? `“${esc(r.record.supportingQuote)}”` : 'none yet'}`);
        if (r.record.notes) md.push(`- **Notes:** ${esc(r.record.notes)}`);
        md.push('', '```sh', `npm run verify:record -- ${r.fact.id} ${sid} --status verified --by "Your Name" --quote "…"`, '```', '');
      }
    }
    writeFileSync(join(outDir, `${skill}.md`), md.join('\n'));

    const header = ['fact_id', 'source_id', 'status', 'claim', 'source_url', 'appears_in', 'tested_by', 'supporting_quote', 'checked_by', 'checked_at', 'notes', 'pre_check'];
    const csv = [header.join(',')];
    for (const r of list)
      csv.push(
        [
          r.fact.id,
          r.sourceId,
          r.record.status,
          r.fact.text,
          r.source?.url ?? '',
          r.appearsIn.map((a) => `L${a.level.number} ${a.card.id}`).join('; '),
          r.testedBy.map((t) => `L${t.level.number} ${t.question.id}`).join('; '),
          r.record.supportingQuote,
          r.record.checkedBy,
          r.record.checkedAt,
          r.record.notes,
          r.record.preCheck,
        ].map(csvCell).join(','),
      );
    writeFileSync(join(outDir, `${skill}.csv`), csv.join('\n') + '\n');
    console.log(`wrote docs/verification/${skill}.md and .csv: ${factsDone}/${facts.size} claims verified`);
  }
}

function sync() {
  const content = load();
  const ledger = readLedger();
  const have = new Set(ledger.map((r) => `${r.factId}|${r.sourceId}`));
  const want = new Set<string>();
  let added = 0;
  for (const c of content.concepts)
    for (const f of c.facts)
      for (const sid of f.sourceIds) {
        want.add(`${f.id}|${sid}`);
        if (!have.has(`${f.id}|${sid}`)) {
          ledger.push({ factId: f.id, sourceId: sid, status: 'unverified' });
          added++;
        }
      }
  const orphans = ledger.filter((r) => !want.has(`${r.factId}|${r.sourceId}`));
  writeLedger(ledger);
  console.log(`added ${added} unverified records`);
  if (orphans.length) {
    console.log(`${orphans.length} records no longer match a fact/source pair (kept for review; delete by hand if intended):`);
    for (const o of orphans) console.log(`  ${o.factId} / ${o.sourceId} (${o.status})`);
  }
}

function record() {
  const [factId, sourceId] = args;
  const status = flag('status') as VerificationRecord['status'] | undefined;
  if (!factId || !sourceId || !status || !(VERIFICATION_STATUSES as readonly string[]).includes(status)) {
    console.error('usage: npm run verify:record -- <factId> <sourceId> --status verified|unsupported|incorrect|unverified --by "Name" [--quote "…"] [--notes "…"]');
    process.exit(1);
  }
  const ledger = readLedger();
  const by = flag('by');
  const rec = setRecord(ledger, factId, sourceId, {
    status,
    ...(by ? { checkedBy: by, checkedAt: flag('date') ?? today() } : {}),
    ...(flag('quote') ? { supportingQuote: flag('quote') } : {}),
    ...(flag('notes') ? { notes: flag('notes') } : {}),
  });
  writeLedger(ledger);
  console.log(`${rec.factId} / ${rec.sourceId} → ${rec.status}`);
  console.log('run npm run verify:report to refresh the checklist');
}

function parseCsv(text: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let cell = '';
  let quoted = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i]!;
    if (quoted) {
      if (ch === '"' && text[i + 1] === '"') (cell += '"'), i++;
      else if (ch === '"') quoted = false;
      else cell += ch;
    } else if (ch === '"') quoted = true;
    else if (ch === ',') row.push(cell), (cell = '');
    else if (ch === '\n' || ch === '\r') {
      if (ch === '\r' && text[i + 1] === '\n') i++;
      row.push(cell), rows.push(row), (row = []), (cell = '');
    } else cell += ch;
  }
  if (cell || row.length) row.push(cell), rows.push(row);
  return rows.filter((r) => r.some((c) => c.trim()));
}

function importCsv() {
  const file = args[0];
  const by = flag('by');
  if (!file) {
    console.error('usage: npm run verify:import-csv -- <file.csv> [--by "Name"]');
    process.exit(1);
  }
  const [header, ...rows] = parseCsv(readFileSync(file, 'utf8'));
  const col = (name: string) => header!.indexOf(name);
  const ledger = readLedger();
  let changed = 0;
  for (const r of rows) {
    const status = r[col('status')]?.trim() as VerificationRecord['status'];
    if (!(VERIFICATION_STATUSES as readonly string[]).includes(status)) throw new Error(`bad status "${status}" for ${r[col('fact_id')]}`);
    const cur = ledger.find((x) => x.factId === r[col('fact_id')] && x.sourceId === r[col('source_id')]);
    const quote = r[col('supporting_quote')]?.trim() || undefined;
    const notes = r[col('notes')]?.trim() || undefined;
    const checkedBy = r[col('checked_by')]?.trim() || by;
    if (cur && cur.status === status && cur.supportingQuote === quote && cur.notes === notes) continue;
    setRecord(ledger, r[col('fact_id')]!, r[col('source_id')]!, {
      status,
      supportingQuote: quote,
      notes,
      ...(status !== 'unverified' ? { checkedBy, checkedAt: r[col('checked_at')]?.trim() || today() } : {}),
    });
    changed++;
  }
  writeLedger(ledger);
  console.log(`updated ${changed} records; run npm run verify:report`);
}

const commands: Record<string, () => void> = { report, sync, record, 'import-csv': importCsv };
const run = commands[command ?? ''];
if (!run) {
  console.error(`unknown command "${command}". Use: report | sync | record | import-csv`);
  process.exit(1);
}
try {
  run();
} catch (e) {
  console.error(`✖ ${(e as Error).message}`);
  process.exit(1);
}
